### ISSUE TITLE
No se puede publicar un anuncio

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#10]
Cuando se intenta da error: "The page isn't redirecting properly".

Aparte, el texto del botón no es "Publicar anuncio" sino "/es/ad/create".

**Comment by andreslucena** [comment]
Estoy revisando el flow, a mi ahora me dejo.

Igual he detectado dos bugs más, los agrego aquí para revisar: 

* Al poner mal el captcha/no rellenarlo, aparece como error (OK) pero no se vuelve a mostrar. 
* Al subir la foto no se muestra bien el thumbnail. Parece que lo sube bien.

**Comment by andreslucena** [comment]
Ya está solucionado todo: 

* Ya no da el error de redirección
* Se ve bien el botón
* Funciona el captcha
* Funciona el thumb 

(Relacionada con #13)
