### ISSUE TITLE
Error al poner una palabra muy larga

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#100]
Al crear una palabra muy larga queda así...
![largo](https://cloud.githubusercontent.com/assets/1123486/9725331/abd0f674-55a9-11e5-8793-bfded2ea7df4.png)

Debería partirse, igual en los comentarios y mensajes.

**Comment by franciscout** [comment]
Vale, ya subi el codigo, No es la mejor solucion (lo que hace ese atributo es "romper" la palabras cuando sobrepasa el ancho asignado) porque tambien 'rompe' por ejemplo "comentario" (en algunas resoluciones aparece como comen-tario) pero es la mas rapida y que implica utilizar las herramientas que ya tenemos disponibles ahora.

Voy a ir buscando otras soluciones, que seguro que habra (por ejemplo, si la palabra sobrepasa determinado numero de letras, ahi romper) pero por ahora ponemos esta y despues la cambiamos cuando haya menos issues abiertos.

**Comment by franciscout** [comment]
solucionado en beta pero dejo abierto para enhancment

**Comment by deivid-rodriguez** [comment]
Cierro esto que creo que la solución actual es suficientemente buena! :wink:
