### ISSUE TITLE
No se pueden borrar regalos

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#101]
Varios usuarios reportan que desde la actualización no pueden borrar regalos.

**Comment by andreslucena** [comment]
Habría qeu revisar los permisos del cancancan

**Comment by apardo** [comment]
https://github.com/alabs/nolotiro.org/pull/109

**Comment by iokese** [comment]
Esto es lo que comentan los usuarios.

![borrar_anuncio](https://cloud.githubusercontent.com/assets/1123486/9915917/6e51add4-5c7f-11e5-9c17-52e16401ae9c.png)

**Comment by andreslucena** [comment]
Ya está subido este cambio a producción. Los usuarios ya pueden borrar sus propios anuncios.
