### ISSUE TITLE
Ha dejado de funcionar el sistema de control de Mayúsculas

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#102]
Eso, que la gente vuelve a poner todo en mayúsculas, a ver si podemos dejarlo como estaba.

**Comment by andreslucena** [comment]
No hay ningún filtro puesto ahora mismo. ¿Que es lo que hacia? ¿No dejaba guardar? ¿Lo convertia a minuscula automaticamente?

**Comment by iokese** [comment]
Lo convertía a minúscula, pero eso perjudicaba la escritura normal y que había mayúsculas correctas que se eliminaban.

Propongo que si pone más de 2 mayúsculas en el título no le deje guardar, y en el texto que se pase todo a minúscula menos la primera letra de la página inicial. ¿Que os parece?.

**Comment by iokese** [comment]
¿?

**Comment by deivid-rodriguez** [comment]
Mmmmm, yo a esto le tengo que dar una vuelta para formarme una opinión. Tengo dudas.

**Comment by iokese** [comment]
Parece que no es muy problemático, lo cerramos.
