### ISSUE TITLE
Revisar cache navegador

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#103]
Parece que el navegador solo cachea los javascript, pero no las imágenes.

**Comment by andreslucena** [comment]
![seleccion_001](https://cloud.githubusercontent.com/assets/717367/10264305/ebe0ecf6-69cc-11e5-879d-a8916b8bd558.png)


Por mi parte lo veo bien, todos los contenidos estaticos de nolotiro.org devuelven 304 a la segunda petición.
