### ISSUE TITLE
Localizacion rota "{:fulll=> ,:short=> }"

### ISSUE THREAD

**Issue by franciscout** [alabs/nolotiro.org#105]
En algunas ocasiones no se cambio del viejo codigo al nuevo en lo respecto a la localizacion, y aparece este tipo de codigo  `{:full=>"Madrid, Madrid, España", :short=>"Madrid"}`

Por ahora lo he econtrado en:

- Cuando buscas terminos [que no estan en otros anuncios](www.nolotiro.org/es/search?utf8=✓&q=algoquenoexiste&ad_type=give&woeid_code=766273&commit=buscar) 

- En el titulo cuando vas a publicar un anuncio.

Si vais encontrando mas, ponerlos aqui.

**Comment by andreslucena** [comment]
Tambien hay qeu revisarlo en el meta-description, por ejemplo: http://nolotiro.org/es/woeid/753692/give?page=2

**Comment by andreslucena** [comment]
Ya lo revise en la beta, esta todo OK, se puede cerrar.
