### ISSUE TITLE
Beta: listado de ciudad mal con adsense

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#106]
En la beta, desde firefox (escritorio, no móvil) veo la publicidad descolocada abajo del todo como en esta captura. 

![hoy](https://cloud.githubusercontent.com/assets/1123486/9833237/619b153a-5955-11e5-8104-63dc72139931.png)

**Comment by franciscout** [comment]
@iokese , ahi esta solucionado en la beta :)

**Comment by iokese** [comment]
Ahora sale muy pequeña a la derecha.

**Comment by franciscout** [comment]
Deje los anuncios igual que siempre, dos anuncios de 160x600 a la derecha... yo lo veo asi: 
![screen shot 2015-09-22 at 11 05 52_cropped](https://cloud.githubusercontent.com/assets/6383798/10014645/02e52026-611b-11e5-9d9d-53a382fbedce.png)

**Comment by andreslucena** [comment]
Cierro este ticket que ya está solucionado. 

Relacionada con #92, hay que revisar donde estan todos los anuncios en todas las paginas en todos los tipos de dispositivos.
