### ISSUE TITLE
Anuncios borrados que aparecen

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#107]
Estos anuncios que adjunto en la captura eran pruebas y están borradas, pero siguen apareciendo y no deberían. Puede que a google no le guste ese contenido inexistente.
![borrado](https://cloud.githubusercontent.com/assets/1123486/9841334/138873f0-5a64-11e5-8109-1c7fc7e54d70.png)

**Comment by andreslucena** [comment]
Esto se debe a falta de refresco de la cache en la busqueda. Al borrar un anuncio no se le avisa a la busqeuda qeu hay qeu quitar eso del indice. Investigar si se puede hacer o preparar un script que rehaga el indice y meterlo en un cron.

**Comment by andreslucena** [comment]
He hecho el script que rehace el indice y lo metí en el cron, ahora a lo sumo debería tardar 1 hora en desaparecer los anuncios de la búsqueda.

**Comment by iokese** [comment]
http://nolotiro.org/es/search?utf8=%E2%9C%93&q=test&ad_type=give&woeid_code=766273&commit=buscar Muchos de esos anuncios ya están borrados, comprobadlo y veréis que esto no se ha solucionado.

**Comment by deivid-rodriguez** [comment]
@iokese Me parece que acabo de ver este mismo bug. Juraría que cuando volví a entrar hace unas semanas borré unos cuantos anuncios antiguos que tenía. En su momento se borraron pero ahora vuelven a estar. Los he vuelto a borrar ver si reaparecen y confirmar el bug.

Entiendo que el borrado es sólo un flag en base de datos, y que alguna tarea asíncrona está tocando este flag y "devolviéndolos a la vida"?

**Comment by andreslucena** [comment]
@deivid-rodriguez eso que comentas puede ser debido a algun fallo relacionado con la migración, que el 10 de septiembre aproximadamente subimos esta versión hecha en Rails. Hasta ahora estabamos utilizando una versión hecha en PHP:  https://github.com/alabs/nolotiro - Probablemente se me haya pasado el flag de la versión antigua. 

Esto que comenta @iokese se trata por el indice de busqueda del Sphinx, que le puse un script para reindexar cada pocas horas (solo tarda unos segundos en reindexar toda la base de datos asi que no necesitamos Deltas con los cambios). Pensé que era esto pero estoy viendo que aun reindexando a mano me sigue apareciendo el anuncio que esta marcado como borrado:

http://nolotiro.org/es/search?utf8=%E2%9C%93&q=testasasasasas&ad_type=give&woeid_code=766273&commit=buscar

En el listado de anuncios del usuario no aparece, o sea que si esta marcado: http://nolotiro.org/es/ad/listuser/id/35240 
Tambien al darle click en el resultado de busqueda, da 404 directamente. 
t
Para el soft delete (el marcado en vez del borrado) estamos usando paranoia. En principio debería ser transparente, asi que hay algo que estoy haciendo mal en algun lado, pero igual quiero probar en local y a ver si se puede hacer un test con esto. 

La configuración de sphinx la tenemos aqui: 
https://github.com/alabs/nolotiro.org/blob/master/config/thinking_sphinx.yml
https://github.com/alabs/nolotiro.org/blob/master/app/indices/ad_index.rb

Pongo en copia a @apardo a ver si se le ocurre alguna solución. 

El script del reindexado del que hablo todavia no lo subi al git, es muy simple: 

´´´
cat /usr/local/bin/reindex_sphinx.sh 
#!/bin/bash

cd /var/www/nolotiro.org/current/ 
RAILS_ENV=production bundle exec rake ts:index
´´´

El resultado da OK y se puede buscar y ver resultados subidos en las ultimas horas, asi que esta funcionando: 

´´´
Generating configuration to /var/www/nolotiro.org/releases/20151017185630/config/production.sphinx.conf
Sphinx 2.0.4-id64-release (r3135)
Copyright (c) 2001-2012, Andrew Aksyonoff
Copyright (c) 2008-2012, Sphinx Technologies Inc (http://sphinxsearch.com)

using config file '/var/www/nolotiro.org/releases/20151017185630/config/production.sphinx.conf'...
indexing index 'ad_core'...
WARNING: collect_hits: mem_limit=0 kb too low, increasing to 26880 kb
collected 121661 docs, 23.5 MB
sorted 42.4 Mhits, 100.0% done
total 121661 docs, 23491252 bytes
total 12.615 sec, 1862083 bytes/sec, 9643.71 docs/sec
skipping non-plain index 'ad'...
total 458 reads, 0.052 sec, 641.1 kb/call avg, 0.1 msec/call avg
total 559 writes, 0.491 sec, 913.7 kb/call avg, 0.8 msec/call avg
rotating indices: succesfully sent SIGHUP to searchd (pid=13751).
´´´

**Comment by deivid-rodriguez** [comment]
Entonces parece un problema específico de la búsqueda, que no aplica el scope de paranoia por algún motivo. Dos preguntas:

- ¿Cuál es el motivo de usar soft-deletes?
- ¿Por qué reindexar en un cron y no programáticamente cuándo se añadan, borren o editen anuncios?

Saludos.

**Comment by andreslucena** [comment]
Lo de usar soft-deletes es más que nada por: 
* Temas legales, si nos denuncian o algo por alguna publicación es necesario que quede registro de eso. 
* Para temas de antispam: quiero investigar usar sistemas como Akismet o similar, para los casos de spam (estafas, prestamos, etc). Guardando estos anuncios podemos entrenar al sistema con estos datos. 

Lo de reindexar con un cron la verdad es porque pensé que iba a ser lo más sencillo y que iba a durar menos tiempo que tener que estar revisando la API de Thinking Sphinx para ver como se hace esto  :P

**Comment by deivid-rodriguez** [comment]
> Lo de usar soft-deletes es más que nada por:
> -   Temas legales, si nos denuncian o algo por alguna publicación es necesario que quede registro de eso.
> -  Para temas de antispam: quiero investigar usar sistemas como Akismet o similar, para los casos de spam (estafas, prestamos, etc). Guardando estos anuncios podemos entrenar al sistema con estos datos.

Yo en general intento evitarlos si no son imprescindibles. Mi expectativa como usuario es que si hago click en "borrar" sobre un contenido mío, los contenidos se borren.

> Lo de reindexar con un cron la verdad es porque pensé que iba a ser lo más sencillo y que iba a durar menos tiempo que tener que estar revisando la API de Thinking Sphinx para ver como se hace esto :P

Nada que objectar a eso! :smile:

**Comment by iokese** [comment]
No recuerdo cual es el límite legal que debemos mantener, voy a revisarlo y propondría que se borren definitivamente al pasar ese límite.

**Comment by iokese** [comment]
Lo he consultado, dicen que sólo debemos guardar los logs de conexión por 1 año (y que incluso eso está en duda). Podemos configurar que se borren, y revisar la BBDD para borrar lo que esté pendiente. Dejo el ticket abierto hasta que se ejecute.

**Comment by deivid-rodriguez** [comment]
Entonces entiendo que para cerrar este ticket habría que:

* Eliminar paranoia.
* Hacer un hard-delete, manualmente o por migración, de los mensajes actualmente marcados como borrados.

¿Estamos de acuerdo?

**Comment by andreslucena** [comment]
Exactamente, creo que no haría falta nada más.

**Comment by deivid-rodriguez** [comment]
Esto ya estaría arreglado! Podemos cerrar la issue.

**Comment by andreslucena** [comment]
Cerrado, gracias @deivid-rodriguez
