### ISSUE TITLE
Mejorar el panel de control

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#108]
Hemos perdido e Phpmyadmin, pero mejor si montamos otro más usable.

Es algo urgente porque no se peuden atender algunas peticiones muy razonables de las usuarias.

**Comment by andreslucena** [comment]
Trabajando en la primera version del /admin. Por cierto no es un bug, es un enhancement (una mejora) :) 

Necesitaría saber que tendría que tener el admin, con un listado de todas las acciones que podrian realizarse.

**Comment by iokese** [comment]
Tenemos que sentarnos a pensarlo, es difícil, algunas notas:

- Poder buscar fácilmente a usuarios por id o nombre
- Poder borrar todos los anuncios de un solo usuario
- Poder buscar en la mensajería cuando recibimos denuncias.
- Bloquear fácil usuarios que no usan bien la herramienta.
- Más por pensar.

**Comment by iokese** [comment]
Ya hay panel de control, pero habría que mejorarlo.

**Comment by deivid-rodriguez** [comment]
Totalmente de acuerdo, no había visto esta lista. La tendré en cuenta para mejorar el panel de admin. Cambio el título para describir mejor la realidad actual.

**Comment by deivid-rodriguez** [comment]
He cambiado el mensaje de @iokese como una TODO listo y marcado lo que ya está implementado (o se añade en #349).

> Poder buscar en la mensajería cuando recibimos denuncias.

Esto ya comenté que creo que es mejor, cuando pase, mirarlo a manubrio.

> Bloquear fácil usuarios que no usan bien la herramienta.

Esto ya se hace desde el perfil de la usuaria en la web. No hace falta añadirlo a la consola de admin también, no?

**Comment by iokese** [comment]
No hace falta meter en el panel lo del bloqueo a un usuario específico.
