### ISSUE TITLE
El Footer se ha roto

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#11]
Se ha comprimido y queda fatal.

**Comment by andreslucena** [comment]
Ya esta funcionando, era un problema con el i18n (no estaba cargando el texto para español, asi que solo mostraba la cadena de nlt.footer_explain). Puede ocurrir con otras traducciones tambien que se me haya pasado. En general si aparece algun texto que empieza con "nlt." es que está ocurriendo esto.
