### ISSUE TITLE
Cambio de regalo  ciudad sin querer

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#110]
Como admin, al cambiar un detalle del regalo de Barcelona (por ejemplo habilitar comentarios que no estaban habilitados) y al darle a guardar, entonces le cambia la ciudad a Madrid (que es la ciudad del administrador). 

Hay que dejar que al cambiar detalles no le cambie la ciudad.

**Comment by apardo** [comment]
No consigo reproducir este error. He editado un anuncio de Vigo, siendo mi ciudad Madrid, y no se ha cambiado la ciudad del anuncio.

**Comment by iokese** [comment]
Parece que ya está arreglado ¿?.

**Comment by iokese** [comment]
Acabo de hacerlo con el usuario iokese y un anuncio de málaga y me lo ha cambiado, sigue pasando :(

**Comment by deivid-rodriguez** [comment]
He intentado reproducir esto y.... no puedo editar ningún campo del anuncio. ¿Esto en producción está funcionando?

**Comment by deivid-rodriguez** [comment]
Lo acabo de probar y no puedo editar anuncios en el admin de producción tampoco. Lo dicho, en breve arreglo todo esto.

**Comment by deivid-rodriguez** [comment]
Esto ya está arreglado, pero ahora mismo SÓLO se permite editar la ciudad del anuncio. Deberíamos definir qué campos queremos que se puedan editar por admin. Entiendo por ejemplo que queremos poder editar el campo "permitir comentarios públicos", no?

**Comment by andreslucena** [comment]
De momento el importante para modificar en el admin es el woeid. Igual podríamos ya dejar todos los campos de Ads habilitados en el AA, y agregar un enlace (solo visible para admins) a este anuncio en el editor de admins.

**Comment by deivid-rodriguez** [comment]
Ah, claro. El tema es que los otros campos ya se pueden editar porque la administradora siempre tiene el link de editar "normal" habilitado. No había caído en esto.

Me gusta tu idea.
