### ISSUE TITLE
Error en mensajería

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#113]
Los usuarios se quejan de un problema en la mensajería. adjunto captura.

![error-mensajes](https://cloud.githubusercontent.com/assets/1123486/9976613/522fda68-5eaf-11e5-9bf5-ee8f03a06c76.png)

**Comment by andreslucena** [comment]
@apardo estabas revisando esto, es lo del other_username. Hay alguna novedad?

**Comment by andreslucena** [comment]
Ya lo tengo resuelto y deployeado a production. El error  era de mensajes antiguos, que algunos no tenian ID de usuario asociado. Ahora mostramos como que se han enviado al usuario "[borrado]", como fix temporal.
