### ISSUE TITLE
No funciona bien publicidad en móvil

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#115]
Parece que no aparece toda, y/o aparece pegada a la derecha haciendo que se descoloque la web.

Pasa en las pantallas de portada, ciudad, mensasjería y regalo. En algunas desaparece el banner de cabecera, y en otras la publicidad está abajo del todo reduciendo el "active view" (debería estar arriba).

**Comment by iokese** [comment]
Además no estamos sirviendo toda la publicidad que corresponde en los móviles, hay que revisarlo bien, propongo reunión.

**Comment by iokese** [comment]
Resoluciones que visitan nolotiro en 18 días.
![captura de pantalla de 2015-10-17 19 15 48](https://cloud.githubusercontent.com/assets/1123486/10561859/8551f9a2-7503-11e5-8336-511c84e5cb08.png)

**Comment by iokese** [comment]
Resoluciones que visitan nolotiro en 18 días.
![captura de pantalla de 2015-10-17 19 21 26](https://cloud.githubusercontent.com/assets/1123486/10561875/5d56f94c-7504-11e5-896d-c5efd7dacfda.png)

**Comment by iokese** [comment]
@andreslucena ¿cómo va esto?.

**Comment by deivid-rodriguez** [comment]
Esto habría que hablarlo tranquilamente en la reunión, me parece.

**Comment by deivid-rodriguez** [comment]
@iokese Cuando puedas me molaría que me pasaras capturas de cómo se ve la publicidad en móvil ahora y como queremos que se vea. Página por página. Si quieres nos juntamos un día y lo vemos.

**Comment by deivid-rodriguez** [comment]
Voy a cerrar esto porque creo que la publicidad ya se muestra siempre y correctamente colocada.
