### ISSUE TITLE
Columnas usuarios y ciudades

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#116]
* Portada: 
** Poner un bloque con 15 usuarios que más regalan último mes.
** Debajo los usuarios que más regalan desde el principio
** Lo mismo para la lista de ciudades.

* Página ciudad: (De momento sólo Barcelona, Madrid, Valencia, Sevilla y Vigo)
** Quitar 1 publicidad lateral y poner lista de 20 usuarios que más regalan la última semana.
** Las que estén a 0 que no aparezca.

Que os parecería en la página ciudad poner otros bloques como:
* Regalos publicados: Hoy, esta semana, este mes, siempre.
* Regalos entregados: Hoy, esta semana, este mes, siempre.

**Comment by deivid-rodriguez** [comment]
Esto ya está implementado.

Queda el segundo tema de estadísticas. ¿Lo seguimos queriendo? A mí me mola la idea, pero no tengo clara la UI.

**Comment by deivid-rodriguez** [comment]
Cierro y delegó la discusión del segundo tema a #425.
