### ISSUE TITLE
Detectar clones presentes y futuros en BBDD

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#119]
Preparar sistema para detectar usuarios clon en la BBDD.
Ejemplos https://github.com/gallir/Meneame/blob/master/scripts/user_clones.py

**Comment by deivid-rodriguez** [comment]
Con devise actualmente guardamos la IP con la que los usuarios se registran. Entiendo que durante el registro podemos comprobar si la IP está entre los usuarios anteriormente bloqueados y en ese caso no permitir el registro. ¿Cómo lo veis?

**Comment by iokese** [comment]
muchos usuarios seguramente nos llegan con proxy, habría que ver si eso no bloquearía a otra gente, o cómo afectaría a los usuarios antiguos si esa IP es dinámica y la tienen otros.

¿Quizás pensar en cookies + IP?.

**Comment by deivid-rodriguez** [comment]
Tienes toda la razón, no es tan sencillo.
