### ISSUE TITLE
Que los usuarios puedan "bloquear" a otros 

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#121]
Que los usuarios puedan bloquear a otros usuarios y no recibir ni más comentarios ni más mensajes.
Además ese usuario bloqueado no podrá ver el perfil del usuario que le bloqueó ni (si es posible) sus regalos.

**Comment by deivid-rodriguez** [comment]
Creo que esta issue sería muy interesante. Creo que casi ningún regalador quiere volver a tener contacto con alguien que se comprometa a recoger un regalo y luego no lo recoja. Este sería un modo muy fácil!

La implemento en cuanto pueda!

**Comment by iokese** [comment]
¿También debería poder desbloquearlo?.

**Comment by deivid-rodriguez** [comment]
Sip, tiene sentido. Cuando me ponga lo tendré en cuenta.

**Comment by iokese** [comment]
¿Y además reportarlo?, tipo Twitter, que pueda reportarlo por SPAM, insultos, etc. 

No se si juntar esto aquí o abrir un nuevo ticket para reportar usuarios, ya que ahora mismo los usuarios deben ir al formulario de contacto y nos reportan generalmente sin datos (enlaces al anuncio o usuario conflictivo), obligándonos a investigar y perder mucho tiempo.

**Comment by deivid-rodriguez** [comment]
Yo creo que un nuevo ticket.

Con respecto a lo de desbloquear. Le he dado otra vuelta y ya no lo tengo tan claro.

* Una vez que una usuaria bloquea a otra, supuestamente ya no tendrá contacto con ella. ¿Qué le podría llevar a desbloquearla? Se me ocurre que le quiera mandar un mensaje porque le interese un regalo que ofrece. En ese caso, simplemente se puede desbloquear automáticamente. Además, entiendo que tras un bloqueo, la bloqueadora sigue viendo la bloqueada normalmente así que no veo que "desbloquear" tuviera ningún efecto visible para quien desbloquea.

- Por otro lado, en caso de bloqueo, la idea sería que la usuaria que bloquea desaparezca totalmente de la vista de la otra, ¿no?

**Comment by iokese** [comment]
+1 a lo de "no desbloquear". Nos lo pedirán más adelante pero de momento es un buen paso.

Sí, al bloquerla debe desaparecer de tu vista, pero también debe dejar de verte a ti (tus anuncios, mensajes, perfil), como si ambos no existierais.

¿Donde debe aparecer la opción de bloquear?. ¿Quizás sólo en la mensajería?.

**Comment by deivid-rodriguez** [comment]
> Sí, al bloquerla debe desaparecer de tu vista, pero también debe dejar de verte a ti (tus anuncios, mensajes, perfil), como si ambos no existierais.

Yo lo había pensado de manera que cuando bloqueas, tú desapareces de la vista de la bloqueada (para que no pueda contactarte, ni entrar en tu perfil, ni mirar lo que publicas, nada). Por el contrario, tú sí que la sigues viendo y si te diera por contactarla en un futuro automáticamente se levantaría el bloqueo. No estoy seguro de que tenga sentido o si es mejor directamente el bloqueo mutuo, pero me parece una opción fácil para permitir una especie de "desbloqueo".

> ¿Donde debe aparecer la opción de bloquear?. ¿Quizás sólo en la mensajería?.

:+1:

**Comment by iokese** [comment]
De momento lo dejaría en boqueo mutuo, sin más vueltas. ¿es muy complejo de implementar?.

**Comment by deivid-rodriguez** [comment]
Yo creo que ninguna de las opciones planteadas es difícil de implementar.

**Comment by deivid-rodriguez** [comment]
@iokese Bueno, tengo una primera versión de esto, aún le queda trabajo pero ya le he dado alguna vuelta. He cambiado un poco sobre la opción que planteamos inicialmente.

Es bloqueo mutuo, como dijimos, pero no es "invisibilidad" sino que lo que desaparece es sólo la capacidad de contactar a la bloqueadora mediante mensajes privados o comentarios en los anuncios (simplemente ocultando los links).

Los motivos son:

* Por un lado, es más fácil de implementar ya que no hay que añadir filtros a los listados ni "ocultar páginas enteras", sólo ocultar links.

* La invisibilidad nunca puede ser total ya que si la usuaria hiciera logout o se conectara desde una máquina nueva sí que va a poder ver a la usuaria que la bloqueó. Por eso creo que no merece la pena "intentar engañarla" de esta manera.

Espero haberlo explicado más o menos...

**Comment by deivid-rodriguez** [comment]
> Por un lado, es más fácil de implementar ya que no hay que añadir filtros a los listados ni "ocultar páginas enteras", sólo ocultar links.

Esto era una tontería, al final tanto una forma como otra es aplicar un sistema de permisos para que ciertas usuarias realicen (o no) ciertas acciones.

He vuelto a la versión inicial que planteamos, con la diferencia de que la usuaria que bloquea sí que puede ver a la otra (simplemente se le ocultan los links). El motivo de esto es que me parece útil que quien bloquea pueda ver la actividad de quien es bloqueado para poder tener información para un posible desbloqueo. Si no, el desbloqueo realmente no tiene sentido...

**Comment by deivid-rodriguez** [comment]
Fixed via #338.
