### ISSUE TITLE
Ciudad de Ecuador

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#122]
Parece que alguien puso un anuncio en un país, el formato es algo raro http://beta.nolotiro.org/es/woeid/23424801/give 
![ecuador](https://cloud.githubusercontent.com/assets/1123486/10567740/e167621c-75d1-11e5-9f3f-2acfda79fa3f.png)

Esa url no debería existir, ¿no?.

**Comment by jipipayo** [comment]
teneis que excluir los woeids de yahoo que no sean type town, bien por type town o por id type (no me acuerdo que numero corresponde a town)

**Comment by deivid-rodriguez** [comment]
Gracias @jipipayo! Lo tendré en cuenta cuando me ponga con esto si no lo solucionas tú u otra persona antes! :wink:

**Comment by deivid-rodriguez** [comment]
Superseded by #173. Cerrando.
