### ISSUE TITLE
Usuarios no pueden publicar en "busco"

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#126]
https://www.facebook.com/nolotiroteloregalo/photos/a.271966516153904.87957.200401059977117/1178360915514455/?type=3&comment_id=1178717112145502&offset=0&total_comments=1&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by deivid-rodriguez** [comment]
Acabo de probarlo y efectivamente el AdBlock también oculta esa área de texto. Saludos!

**Comment by andreslucena** [comment]
@deivid-rodriguez gracias por la prueba.

@franciscout estoy de acuerdo con lo que decis. Mejor mostrar un alert en rojo en el header cuando se tiene el adblock activado, diciendo que hay algunas cosas que pueden dejar de funcionar y que deberías desactivar el adblocker. (Por ejemplo las imagenes de los anuncios tambien desaparecen porque encuentra /ads/ en la URL).

**Comment by deivid-rodriguez** [comment]
@andreslucena De nada. Si me permitís mi opinión, creo que se tarda lo mismo en arreglar las dos cosas que no funcionan que en detectar adblock y añadir una alerta. Otra cosa es que queráis evitar el uso de AdBlock en nolotiro. En ese caso, dejar la página "no funcional" es una buena idea. :)

**Comment by iokese** [comment]
@deivid-rodriguez Correcto. Este bug lo heredamos del código original, al menos ayuda a financiar un 15% de lo que realmente cuesta mantenerlo (moderación + incidencias + flames + código + servidor + dns + backup), casi lo consideraría una feature :)

+1 a ese banner en rojo avisándoles que lo desactiven.

**Comment by deivid-rodriguez** [comment]
Ya por curiosidad, ha cambiado algo la publicidad en la página? Hacía un par de años que no usaba nolotiro y muy posiblemente sea mi percepción la que ha cambiado pero tengo la sensación de que es más invasiva que antes. Me refiero al banner frontal (sólo recuerdo los laterales y los que se intercalan entre los anuncios), y a que los banners sean animados.

En cualquier caso no me malinterpretéis, entiendo y respeto totalmente que no queráis perder dinero con la página y que pongáis publicidad para financiarla. Es sólo una percepción a nivel de usuario.

**Comment by iokese** [comment]
A mi tampoco me convence. Los animados ya son de antes, pero el de cabecera y alguno extra lateral son nuevos y el cambio es muy reciente, estamos probando dónde rinden mejor, pero deberían reducirse. Además siempre lo hemos mantenido con poca publicidad y filtrando la calidad de la misma, es bueno mantener esa línea y sí, nos estamos saliendo un poco.

El problema de fondo efectivamente es la autofinanciación, la capacidad de mantener el sitio y poder mejorarlo sin precarizar a nadie. Nolotiro bajó mucho en tráfico este año pasado, le aportamos mucho pero no podemos mantener este ritmo mucho tiempo, debe autogestionarse y está lejísimos de poder hacerlo. No es el camino que queremos tomar, pero de momento ayuda a que sea menos duro. El camino real pasa por multiplicar las ventajas que ofrece, por que le sea más útil a la gente para evitar que se tiren miles de cosas a la basura. Si conseguimos que sea más útil y tenga más usuarios podríamos reducir más la publicidad.

Te agradecemos mucho tanto el código como la sinceridad. No te malinterpretamos, creo que coincidimos. Somos una pequeña asociación cultural que asumimos esta pérdida por años, nuestro objetivo es que la gente se organice y no se tiren cosas. Todo lo que da o lo que  pueda dar en un futuro nolotiro se seguirá gastando en mejorarlo/potenciarlo, no en yates :)

En eso estamos, primero solucionando bugs de la migración y añadiendo pequeñas funcionalidades, en breve toca pensar en "gammificar" el sitio, si logramos que más ciudades se activen el impacto de la herramienta será todavía mayor.

Bienvenido, ¡y muchas gracias por interesarte!

**Comment by deivid-rodriguez** [comment]
Sí, coincidimos! Nolotiro me parece una idea genial y espero que siga adelante y que mucha gente lo use. Yo personalmente lo recomiendo a poco que venga a cuento. :)

¡Un saludo!

**Comment by iokese** [comment]
Si te animas un día podemos buscar dónde discutir las próximas mejoras, nos viene muy bien la visión de un usuario de la aplicación que además programa. Son cosas como budgets, pero pueden conllevar un gran cambio en la aplicación. Mejor seguimos por otro sitio y dejamos este para el ticket :)

**Comment by deivid-rodriguez** [comment]
@iokese Me parece bien!

**Comment by iokese** [comment]
Parece que también tiene problemas para publicar regalos, meto por aquí un correo que llegó por el formulario: "User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

NO CONSIGO PUBLICAR MI ANUNCIO. VERIFICO LAS IMAGENES , LE DOY A ENVIAR Y NO SIGUE"

**Comment by andreslucena** [comment]
Ya está solucionado, cambiando las rutas de imagenes para que no aparezca "/ad/" en la URL.

**Comment by deivid-rodriguez** [comment]
Que bien que decidistéis arreglar esto!!
