### ISSUE TITLE
Url no encontrada al acceder a un usuario con espacios en el nombre

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#127]
Un usuario me ha escrito un mensaje y al intentar acceder a su perfil desde la conversación, me da un 404. Por lo que veo, debe de haber alguna configuración en el servidor que elimina los espacios de la URL, ya que el mi entorno de desarrollo funciona correctamente.

Ahora abro una PR arreglando el error usando la URL con el id del usuario, aunque supongo que al tema de los espacios también habría que echarle un ojo.

Saludos!

![captura de pantalla_2015-10-25_12-21-02](https://cloud.githubusercontent.com/assets/2887858/10715328/9432d566-7b13-11e5-80ec-58d3cdd0054f.png)

**Comment by andreslucena** [comment]
Exactamente eso es lo que ocurre, teniamos una config en el lado del nginx que quitaba los espacios con URL porque antiguamente habia una URL que estaba mal generada y tenia muchos espacios. Le quito este redirect y tambien acepto tu PR asi somos siempre consistente con esa URL.

**Comment by deivid-rodriguez** [comment]
Veo que ya has quitado la configuración del servidor. ¡Gracias!
