### ISSUE TITLE
Incidencia login

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#131]
Una usuarioa nos comenta: "Tengo problemas para acceder, cada vez que intento entrar me dice que no reconoce ni mi clave ni mi correo. He cambiado la clave tres veces y puedo acceder, pero cuando me desconecto e intento volver a entrar nunca puedo acceder, cual es el problema?"

**Comment by deivid-rodriguez** [comment]
He intentado reproducir esto y he descubierto algo peor. El email de reseteo de contraseña no me llega... :S

**Comment by andreslucena** [comment]
:( 

Se me ocurre que puede estar relacionado con usuarios legacy, que no este teniendo en cuenta las contraseñas.

@deivid-rodriguez  Lo del email de reseteo de contrasesña lo has probado en desarrollo o en produccion? Por las dudas pasame el id de tu usuario asi lo reviso en la beta.

**Comment by deivid-rodriguez** [comment]
En producción, pero si quieres lo pruebo en desarrollo también, aunque supongo que si es un problema de usuarios legacy no lo voy a poder reproducir. Mi id de usuario es 5851.

**Comment by deivid-rodriguez** [comment]
Buenas, disculpad la falsa alarma. El bug de los reseteos desaparecidos no es tal.

Al parecer google ha añadido dos nuevas "pestañas" a gmail, que están ocultas por defecto: "Notificaciones" y "Foros", y estos mensajes de nolotiro los pasa directamente a "Notificaciones". Hoy haciendo una búsqueda desde el móvil, por casualidad encontré los correos.

No me quiero imaginar la cantidad de sitios en los que va a pasar esto... :S

**Comment by deivid-rodriguez** [comment]
Vale, no. En realidad google muestra todos los mensajes en la bandeja de entrada principal. La culpa era de un antiguo filtro que tenía habilitado para las notificaciones de nolotiro.

En cualquier caso, no hay bug.

**Comment by andreslucena** [comment]
Ok @deivid-rodriguez me quedo mas tranquilo, que no conseguia reproducirlo en mi base de datos en local y tenia pendienete a descargarla de nuevo para ver que podia pasar.

**Comment by deivid-rodriguez** [comment]
Jejeje me alegro :flushed:

**Comment by iokese** [comment]
¿Cerramos el ticket?.

**Comment by deivid-rodriguez** [comment]
@iokese Perdona por tardar tres meses en contestar :). Si no ha habido más incidencias de este tipo... sí, cerrémoslo!
