### ISSUE TITLE
Actualizar Ruby

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#138]
Me gustaría actualizar Ruby a 2.3.0 en la app. Cómo lo veis? La compatibilidad hacia atrás de Ruby es buenísima, y las mejoras de rendimiento gratis molan. :)

**Comment by andreslucena** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
Genial! Yo hago una PR pero entiendo que habrá que actualizar manualmente los servidores también.
