### ISSUE TITLE
Diseño responsivo

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#14]
Gran parte del tráfico viene de dispositivos móviles. Deberíamos terminar de hacer el responsivo para que se vea bien en las siguientes resoluciones (sacadas de Google Analytics): 

360x640 
320x480 
480x800 
768x1024  
320x534

A día de hoy ya hay algo básico, principalmente lo que está fallando es el Adsense.

**Comment by andreslucena** [comment]
@franciscout ya subió el código que tenía, se puede ver funcionando en http://beta.nolotiro.org/ 

Lo que más guerra da es lo del Adsense. Hay un bug que es que no se ve con Firefox, lo está revisando. 

Por otro lado tener cuidado al hacer pruebas ya que el responsivo del Adsense funciona en la carga inicial de la página, pero al redimensionar la ventana no se adaptará como se hace normalmente. El flujo debería ser redimensionar la ventana y volver a cargar la página.

**Comment by andreslucena** [comment]
Hay algunos problemas en páginas puntuales: 

* Listado de anuncios (desplazamiento de adsense): http://beta.nolotiro.org/es/woeid/766273/give 
* Anuncio particular (desplazamiento de adsense): http://beta.nolotiro.org/es/ad/190055/hamaca-y-ropita-de-bebe
* Anuncio particular (con sesion iniciada, textfield de mensaje): http://beta.nolotiro.org/es/ad/190055/hamaca-y-ropita-de-bebe 
* Listado de mensajes (con sesion iniciada, tabla de mensajes no es responsiva): http://beta.nolotiro.org/es/message/list 
* Mensaje particular (con sesion iniciada, revisar todo)

**Comment by andreslucena** [comment]
Otros errores de desplazamientos en las siguientes páginas: 

* ads#show adsense mal
* woeid#show tendrian qeu ser 2
* messages#list adsense derecha
* listall(woeid#show) falta publicidad

Pongo en copia a @iokese por si hay algun otro adsense que se vea mal.

**Comment by iokese** [comment]
En el listado de ciudad a veces aparece la publicidad "160x600" y a veces la "486x60" en el centro de la lista de anuncios. Para confirmarlo entrar en http://beta.nolotiro.org/es/woeid/766273/give?page=2 y avanzar o retroceder página.
En cualquiera de los casos, aunque ponga la publicidad "160x600", sigue reservando el espacio en la lista de anuncios horizontales para la publicidad 486x60.

La publicidad tamaño  486x60 de momento solo debe estar en la portada. Hay que eliminarla del listado de ciudades.

**Comment by andreslucena** [comment]
Ya estamos terminando de aplicar el responsivo en todas las páginas. En caso de encontrar errores puntuales abrir tickets para ellos.
