### ISSUE TITLE
Migrar de Sphinx a ElasticSearch para el buscador

### ISSUE THREAD

**Issue by apardo** [alabs/nolotiro.org#141]
Buenas,

propongo migrar de Sphinx, algo anticuado ya, a ElasticSearch. Tienes más opciones y para el futuro deploy nos facilita la vida.

¿Cómo veis de complicado actualizar la aplicación?

Ciao

**Comment by deivid-rodriguez** [comment]
Estaría bien, sip. Yo con ElasticSearch tengo experiencia, pero Sphinx la verdad es que nunca lo he usado. Así que migrar no sé cómo de complicado sería.

**Comment by andreslucena** [comment]
A nivel de configuraciones de ThinkingSphinx no hacemos cosas raras: 

https://github.com/alabs/nolotiro.org/blob/master/app/indices/ad_index.rb
https://github.com/alabs/nolotiro.org/blob/master/config/thinking_sphinx.yml

Lo único que la gema que usamos ahora mismo para los mensajes ([mailboxer](https://github.com/mailboxer/mailboxer)) tiene configurado para usar sphinx o solr (no tiene soporte para ElasticSearch). Tampoco es una feature que estemos usando ahora mismo y que igual podriamos replicar con ES (o incluso podriamos hacerles un PR si lo necesitamos): 

https://github.com/alabs/nolotiro.org/blob/878c8cc16c6f7ceb68131ef9e56d6b31fe96c2f2/config/initializers/mailboxer.rb#L14

**Comment by apardo** [comment]
Este tutorial deja bien claro como va la integración con Rails:
http://www.sitepoint.com/full-text-search-rails-elasticsearch/

**Comment by deivid-rodriguez** [comment]
Pues por lo que parece no va a ser tan complicado! :smiley:

**Comment by andreslucena** [comment]
Por mi lo que sea más facil de hacer deploy/pruebas en local. Otra opción es migrar a postgres (que alguna vez lo hablamos) e investigar con pg_search. Como lo ven?

**Comment by deivid-rodriguez** [comment]
Para lo que lo usamos `pg_search` podría ser suficiente sí, y es builtin. A mí me mola mucho esta idea, pero hay que ver cómo de factible es. Usamos algún feature específico de MySQL?

**Comment by apardo** [comment]
En el schema.rb no veo nada específico de MySQL. Con Postgres también tendríamos emojis en la DB :) que en MySQL es un cristo.

**Comment by deivid-rodriguez** [comment]
Genial, pues es cuestión de ponerse y probar! Entonces el plan es:

* [ ] Migrar de MySQL a postgresql.
* [ ] Migrar de Sphinx a pg_search.

Sí?

**Comment by apardo** [comment]
Un rake db:schema:load con postgres no da ningún error.

**Comment by jipipayo** [comment]
Postgres for the win!

**Comment by deivid-rodriguez** [comment]
Voy a cerrar esta issue de momento, ya que hemos dejado de usar thinking-sphinx y no está claro que (de momento) necesitemos un buscador más complejo.
