### ISSUE TITLE
Añadir enlace directo a la lista de regalos en el menú principal

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#143]
Otra cosa que he echado de menos mientras gestionaba el montón de cosas que estoy regalando entre ayer y hoy es una manera fácil de acceder mi lista de regalos desde cualquier lugar, por ejemplo, desde una conversación.

Un iconito de un regalo junto al sobrecito de mensajes podría ser una solución fácil y práctica de momento.

¿Qué os parece?

**Comment by andreslucena** [comment]
En principio con #223 no haría falta, el mismo perfil (enlace con tu nombre) tiene el listado de anuncios, datos de usuarios y todo lo qeu pueda necesitar.

**Comment by deivid-rodriguez** [comment]
:+1: Correcto, cierro esto entonces!
