### ISSUE TITLE
Arreglar flow de confirmación de cuenta

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#149]
Los tests de Eneko hacen pensar que uno de los mayores motivos de abandono es el proceso de confirmación de cuenta. Para arreglar este flow, reflexiones:

- Necesitamos confirmaciones de cuenta? Normalmente el flow de confirmación se utiliza para asegurar tanto que el usuario tiene un email válido y accesible (para newsletter, notificaciones, etc) como sobre todo para que ningún usuario se registre en nombre de otro (para spamearlo por ejemplo). Yo diría que está bien tenerlo, pero creo que está bien replanteárselo igualmente. Quizá podríamos permitir el acceso "no confirmado" por un tiempo?

- Realmente necesitamos enviar los emails de confirmación de manera asíncrona? Esto me parece totalmente overkill y confunde mucho tener que esperar 10 minutos a que llegue el mail de confirmación. Esto lo demuestran muy bien los vídeos de Eneko. Si decidimos que no es necesario, arreglar esto parece tan sencillo como eliminar `devise-async`...

Opiniones?

**Comment by iokese** [comment]
Necesitamos las confirmaciones, +1 a que sea instantáneas.

**Comment by deivid-rodriguez** [comment]
Perfecto, mañana hago PR para esto!
