### ISSUE TITLE
Usar Passenger + nginx en producción

### ISSUE THREAD

**Issue by apardo** [alabs/nolotiro.org#16]
Simplifica el deploy y mejoró mucho en los últimos años:
https://www.phusionpassenger.com/#about

**Comment by andreslucena** [comment]
Ya está instalado, con los repositorios de Ubuntu como explican aqui: 

https://www.phusionpassenger.com/documentation/Users%20guide%20Nginx.html#install_on_debian_ubuntu

He dejado la configuración de unicorn activada, y los virtualhosts de nginx de los dos para probar. Esta activado tanto para production como para staging.
