### ISSUE TITLE
Añadir filtros disponible/reservado/entregado en la lista de anuncios del usuario

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#161]
Resultaría muy útil y parece sencillito de implementar.

Y además es consistente con la UI, ya que el tab de mensajes ya tiene subtabs (enviados, recibidos, papelera), así que se aplicarían los mismos estilos.

**Comment by andreslucena** [comment]
Yo tengo mis dudas con esto, de que las usuarias puedan contactar a otras que ya entregaron o reservaron el objeto. Igual en los ya entregados por lo menos quitar el link a "Contactar con el anunciante"?

**Comment by deivid-rodriguez** [comment]
Tienes toda la razón, yo lo miro desde el punto de vista de "la regaladora". Resulta muy útil poder ver qué regalos tienes reservados, cuáles has entregado ya y cuáles tienes por entregar. Ahora mismo no hay forma de hacerlo.

Pero efectivamente no deberían poder enviarse mensajes a regalos entregados o reservados. Esto igual lo abrimos como un bug a parte no?
