### ISSUE TITLE
No mostrar links de "Enviar mensaje privado al anunciante" para regalos reservados y entregados

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#171]
Mencionado por @andreslucena en #161.

Podríamos prohibir esto a nivel controlador también, no sólo a nivel interfaz, pero teniendo en cuenta que el tema de los mensajes va a cambiar radicalmente en un futuro más o menos cercano (#130) creo que no merece la pena.

**Comment by jipipayo** [comment]
+1
