### ISSUE TITLE
excluir los woeids que no sean localidades (ciudad, pueblo, o inferiores)

### ISSUE THREAD

**Issue by jipipayo** [alabs/nolotiro.org#173]
hay que excluir cualquier woeid que no sea type="town".

Ahora mismo al buscar localidades nos pueden salir resultados de niveles superiores: pais, region, etc y da pié a que el usuario se confunda y ponga anuncios en lugares erróneos como "España" pais.

https://nolotiro.org/es/woeid/23424950/give

tocar el helper de location y excluir con woeid type ="town"

tal vez haya que hacer algo con las rutas y devolver un 404 cuando el woeid no corresponda a una localidad.

**Comment by deivid-rodriguez** [comment]
Implementar esto arreglaría #122, no?

**Comment by deivid-rodriguez** [comment]
@jipipayo He desplegado los cambios en tu PR. #172 se ha arreglado, pero esta issue no estoy seguro. Entiendo que las siguientes URLs ahora no deberían existir, no?

https://nolotiro.org/es/woeid/23424801/give
https://nolotiro.org/es/woeid/23424950/give

**Comment by jipipayo** [comment]
cierto, hay que cascar un 404 desde el controlador si el woeid no es del typo 7 (town)
Reabro esa.
Moved los anuncios que hubiera por error en la db, porque ya no estarian accesibles esos woeids una vez hecho el cambio. Creo recordar que eran de Ecuador?
