### ISSUE TITLE
Actualizar las gemas que usamos en la aplicación

### ISSUE THREAD

**Issue by apardo** [alabs/nolotiro.org#177]
Gemnasium nos dice que tenemos algunas gemas sin actualizar:
https://gemnasium.com/alabs/nolotiro.org

**Comment by deivid-rodriguez** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
Voy a cerrar esta issue porque creo que no tiene sentido tenerla abierta. Aunque actualicemos las gemas, quedarán de nuevo desactualizadas en un futuro. Tener la app lo más actualizada posible es un trabajo continuado, no un ticket que se pueda cerrar.
