### ISSUE TITLE
hacer que las urls sin locale param redir a un 404 (o en su defecto a la url con el param locale default)

### ISSUE THREAD

**Issue by jipipayo** [alabs/nolotiro.org#179]
ahora mismo si ponemos una url sin param locale. es, en, it, etc...
da un 200 y pinta la pagina con el locale de session o por defecto.

https://nolotiro.org/woeid/753692/give
esto es muy malo para seo.

hacer que sin locale de un 404 not found, y añadir en todas las plantillas los codigos de link rel alternate correspondientes.

http://www.victorberroya.com/hreflang-seo-internacional/

**Comment by deivid-rodriguez** [comment]
:+1: a los hreflang. A lo otro también :+1: que tú eres el experto de esto pero me molaría una referencia o explicación. Para aprender!

**Comment by jipipayo** [comment]
del link rel alternate os he pueto un enlace, no tiene misterio, y sobre el redir a 404, pues tampco tiene mucho misterio, simplemente es evitar urls diferentes pero con el mismo contenido, si damos un 200 en 
nolotiro.org/ad/2323  y tambien lo damos con sus respectivos langs pues google ve que es una pagina duplicada porque ve que tiene el mismo contenido aunque las urls sean distintas.

**Comment by deivid-rodriguez** [comment]
Sí, el link me lo leí y mola añadir lo de los hreflang!

Lo otro, creía que era algo relacionado con el lenguaje y tal y busqué en google algo como "multilanguage site urls without locale bad for seo", pero no encontré nada. Ahora veo que el tema no tiene nada que ver con locales sino con tener distintas urls sirviendo el mismo contenido, que entiendo que es algo que google puntua bajo.

En cualquier caso, diría que este es un problema que nos afecta muy tangencialmente. Date cuenta que **todas** las URLs que genera la aplicación se generan **con locale**. Simplemente nolotiro responde a urls sin locale, pero cualquier click sucesivo será en un link con locale. Salvo que alguien que sepa que las URLs funcionan sin locale decida enlazarnos mediante una URL sin locale, los bots de google nunca van a indexar URLs de nolotiro sin locale. Y en ese caso, sería sólo una (o el número de links que nos hayan enlazado de esta peculiar forma). Me explico? Tiene sentido esto que digo?

**Comment by jipipayo** [comment]
hombre si tiene que ver con idiomas y con la inclusión de rel alternate. google relaciona los idiomas para considerar si el contenido es el mismo o es una version en otro idioma.
Lo que dices sobre que afecta tangencialmente... pues no se que decir, que haya urls duplicadas es malo, y no hay mucho que debatir. y lo de pensar que por que esas urls no las tenemos añadidas en la navegación no las vaya a encontrar google, pues tampoco funciona así:** las encuentra**. Las encuentra y las suma y las rankea como dupes, eso es asi, no me voy a molestar mucho en explicarlo. 
y ya olvidando el seo, pues es que es feo, igual que el estilo de código hay que cuidar la aplicación en si. no tiene sentido que una url sin lang duplique la funcionalidad de una url con lang. Esta mal. al menos redir a la url con lang por defecto.

**Comment by deivid-rodriguez** [comment]
hombre, si tiene que ver con idiomas y con la inclusión de rel alternate: google relaciona la url los idiomas para considerar si el contenido es el mismo o es una version en otro idioma.

Ok, tiene sentido.

> Las encuentra y las suma y las rankea como dupes, eso es asi, no me voy a molestar mucho en explicarlo.

:cry: :cry: Me gustaría aprender más y que compartamos lo que sabemos. Yo creía que google exploraba la web clickando links como hacen los seres humanos, y que si no encontraba cierto link no lo indexaba.

> y ya olvidando el seo, pues es que es feo, igual que el estilo de código hay que cuidar la aplicación en si. no tiene sentido que una url sin lang duplique la funcionalidad de una url con lang. Esta mal. al menos redir a la url con lang por defecto.

De primeras te creo porque tú sabes mucho, pero investigaré más para formarme una opinión que me convenza... De primeras desde luego feo no me parece. Rails provee de manera builtin soporte para parámetros opcionales en las URLs (ahora mismo lo utilizamos).  _"Genérame rutas con un segmento para el locale. Si viene sin locale, usa el que yo te diga que es el locale por defecto"_. Desde mi ignorancia me parece limpio.

**Comment by deivid-rodriguez** [comment]
He hecho una pregunta aquí para intentar aprender algo: http://webmasters.stackexchange.com/questions/91842/is-using-optional-url-segments-bad-for-seo.

Si tienes ganas de ayudarme a mejorar la pregunta (me ha dado un aviso de que mi pregunta era "likely to be closed because of being subjective"), o incluso ganas de contestar, adelante! :wink:

**Comment by jipipayo** [comment]
tienes 2 puntos de entrada para un mismo contenido, está duplicado.

https://moz.com/learn/seo/duplicate-content

tiene gracia que lo entiendas con metodos y clases y no con urls y contenidos XD

**Comment by deivid-rodriguez** [comment]
Muchas gracias por la referencia! Tiene sentido. Parece que la solución más fácil es dejar las URLs sirviendo contenido duplicado e informar a google de la versión canónica de la URL usando lo de `rel=canonical`. Hacemos eso?

> tiene gracia que lo entiendas con metodos y clases y no con urls y contenidos XD

Qué subjetivo es el humor! :)

**Comment by jipipayo** [comment]
Yo añadiría rel canonical , rel alternate langs y un 404 como un castillo (esto es opcional y mi manera que paso a explicarte).
Efectivamente con rel canonical y rel alertante "basta", pero con un 404, le estas diciendo a google: camino equivocado, no sigas por aquí, no hay nada, no crawlees las urls que hay en esta página que tampoco llevan param lang en la url.
Y como efectivamente las rutas y los langs están muy bien integradas y va a ser muy raro que un user de nolotiro vaya a una url sin lang, pues esto se hace casi exclusivamente para robots. "Ahorrate los ciclos de cpus robot, guardate esta url y las urls hijas y márcala como 404, no vuelvas a visitarla", de la otra forma puede volver. 
Date cuenta que si engancha googlebot una url sin lang, puede tirar por ahi, y crawlearte nolotiro entero sin lang. ¿para que? ¿porque? que luego al final google sabe que la buena es la que lleva lang... vale, pero ¿y si le puedes ahorrar ese tiempo? mientras crawlea esas urls que van a ser descartadas podría haber estado crawleando las buenas.
Ya hablando de arquitectura de la información, semanticamente si no lleva lang una url , debería responder con eso : no tenemos lenguaje en la url , por lo tanto no tengo una página para darte , te puedo redirigir a la que tengo por defecto (y porque en default español?), te puedo hacer una heurística de tu navegador+ location ip + bla bla.. meh: al final lo mejor es cerrar esa puerta para el bot.

**Comment by deivid-rodriguez** [comment]
> Efectivamente con rel canonical y rel alertante "basta", pero con un 404, le estas diciendo a google: camino equivocado, no sigas por aquí, no hay nada, no crawlees las urls que hay en esta página que tampoco llevan param lang en la url.

El tema es que en nolotiro no hay urls sin param lang en la URL (o no debería). Si sigue crawleando va a crawlear siempre URLs con lang.

> Date cuenta que si engancha googlebot una url sin lang, puede tirar por ahi, y crawlearte nolotiro entero sin lang.

Pero cómo funciona el bot? cómo hace para escanear? Yo creía que escanea la web como un árbol gigante. En plan, llega a una URL (nodo padre), se apunta todas las URLs salientes (nodos hijos) y escanea cada subárbol. Si es así, todos las URLs salientes tienen lang.

**Comment by deivid-rodriguez** [comment]
Por otro lado, tiene sentido añadir el canonical y responder 404? No son opciones excluyentes?

**Comment by jipipayo** [comment]
tienes razón en el caso de nolotiro al llegar a https://nolotiro.org/ad/205862/tablon-pino-macizo-200cm-x-15cm

los links llevan lang, pues un problema menos.

pero vamos que si tu lo ves bien y no ves que haya 2 puntos de entrada para un mismo contenido pues no se que mas decir. XD

**Comment by jipipayo** [comment]
![captura_nolotiro_ad_sin_lang](https://cloud.githubusercontent.com/assets/1165/14156892/ff1239cc-f6c8-11e5-93ec-fd7e441a60a5.png)

mira un anuncio indexado sin lang, el de la flanera de plastico ikea...
con el rel canonical se arregla y con rel alertane lo mejoras, pero que cuesta cascar un 404 o un 301 y cerrar ese camino, es que no entiendo que problema hay en dejarlo todo mas ordenado.

**Comment by deivid-rodriguez** [comment]
> tienes razón en el caso de nolotiro al llegar a https://nolotiro.org/ad/205862/tablon-pino-macizo-200cm-x-15cm
> los links llevan lang, pues un problema menos.

Genial estar ya en la misma página en esto.

Yo según lo que he entendido hasta ahora veo propuestas dos soluciones para el contenido duplicado:
* No generar contenido duplicado. Para esto pasaríamos a devolver 404 cuando las URLs no llevan lang.
* Mantener el contenido duplicado e informar de ello a Google. Para ello usaríamos lo de `rel=canonical`.

Lo que no entiendo es cómo funcionan las dos juntas. Si sólo hay una versión de cada URL, para qué sirve lo de `rel=canonical`?

**Comment by deivid-rodriguez** [comment]
> con el rel canonical se arregla y con rel alertane lo mejoras, pero que cuesta cascar un 404 o un 301 y cerrar ese camino, es que no entiendo que problema hay en dejarlo todo mas ordenado.

Problema ninguno, sólo intento entender por qué hacemos las cosas para aprender algo!

**Comment by jipipayo** [comment]
mira, google ya ha enganchado por defecto sin lang como el idioma español:
https://www.google.es/search?q=site:nolotiro.org&start=10

es que lo que no entiendo es porque te cuesta tanto entender esto y no lo mismo aplicado a una clase o una funcion. XD
me choca mucho jaj

**Comment by deivid-rodriguez** [comment]
> es que lo que no entiendo es porque te cuesta tanto entender esto y no lo mismo aplicado a una clase o un controlador. XD
> me choca mucho jaj

Creo que con este tipo de frases no esperas ninguna respuesta así que no diré nada.

Con respecto al tema que debatimos, estoy en plena investigación! En cuanto tenga algo os cuento conclusiones.

**Comment by deivid-rodriguez** [comment]
@jipipayo He investigado un poco más.

Cuando abriste la issue y sugerías lo de los `rel=alternate` y los `hreflang` creía que había consultado [el código](https://github.com/alabs/nolotiro.org/blob/14fc7f593b23c6c4103ffb757702315d38b5b915/app/views/layouts/application.html.erb#L23-L26) primero.
 
Nuestra versión actual ofrece alternativas a cada página en cada locale soportado, y además considera la primera URL sin locale nada más llegar al sitio como una página no dirigida a usuarios con un lenguage/región específica (usando `x-default`). Los últimos cambios en esas líneas los ha ido haciendo @andreslucena intentando hacer feliz a google y sus herramientas (https://github.com/alabs/nolotiro.org/commit/e015d7e0c26f35e661fa14f1d484b4cc601ee811, https://github.com/alabs/nolotiro.org/commit/936c650db2f2d92b2b3ce83d010afdb10eb4227e).

Tal como están ahora las cosas, esa primera URL sin locale parece un momento perfecto para detectar el lenguaje del navegador (o el lenguaje preferido del usuario) y generar las URLs sucesivas con un locale adecuado (obviamente manteniendo el selector de lenguaje).

También he investigado [cómo se hacía](https://github.com/alabs/nolotiro/blob/f5f9f1b28b5301f611a1106e46bc76d3a1f05651/application/controllers/helpers/Checklang.php#L21-L28) en la antigua versión de nolotiro y se hacía justamente esto, aunque de manera un poco más exhaustiva (miraba también la sesión, por ejemplo). También tenía otra mejora sobre la versión actual: una vez deducido el locale, se añadía el `canonical` apuntando a la URL canónica correspondiente ([1](https://github.com/alabs/nolotiro/blob/f5f9f1b28b5301f611a1106e46bc76d3a1f05651/application/controllers/IndexController.php#L45-L46), [2](https://github.com/alabs/nolotiro/blob/f5f9f1b28b5301f611a1106e46bc76d3a1f05651/application/controllers/AdController.php#L66-L67), [3] (https://github.com/alabs/nolotiro/blob/f5f9f1b28b5301f611a1106e46bc76d3a1f05651/application/layouts/scripts/header_common.phtml#L33-L36)).

Por mi parte, :+1: a recuperar lo que se hacía antes. :-1: a dar 404 en las URLs sin locale.

**Comment by apardo** [comment]
Yo creo que hay que hacer lo que dice Remeseiro, devolver 404 y tal. Concretamente lo haría como lo hacía antes StackOverflow y todos sus sites verticales:
http://meta.stackexchange.com/questions/14056/seo-in-stack-overflow/42105#42105

El caso es que ahora StackOverflow no usa esta técnica, dejaron de usar meta tags.

**Comment by deivid-rodriguez** [comment]
@apardo no encuentro ninguna mención al 404 en el link que pones... Yo de momento voy a añadir lo del `canonical`, que en eso parece que estamos todos de acuerdo.

Aún no me ha quedado claro qué sentido tendrían los `rel=canonical` si damos 404 (qué cada url única añada un canónical... a sí misma?). En cualquier caso, con canonicals o sin canonicals, reitero que dar 404 me parece una mala idea, más con el nivel de indexación que tienen nuestros links sin locales en google (como explico en el mensaje anterior, porque se lo hemos dicho nosotros).

**Comment by deivid-rodriguez** [comment]
Cierro esto porque hemos vuelto a lo que hacía la v2 y el SEO empieza a mejorar. Cualquier cosa relacionada la discutimos en una nueva issue.
