### ISSUE TITLE
Mensajes inglés al añadir un regalo

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#18]
Al añadir un anuncio, si el título o el cuerpo es demasiado corto da el siguiente mensaje que no es muy comprensible:

"2 errors prohibieron que se guardase este anuncio:

    Title es demasiado corto (10 caracteres mínimo)
    Body es demasiado corto (30 caracteres mínimo)"

**Comment by andreslucena** [comment]
Solucionado, falta comprobar y cerrar ticket.

**Comment by iokese** [comment]
Perfecto, cierro.
