### ISSUE TITLE
Ponernos de acuerdo y aplicar un estilo de código uniforme

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#180]
Soy un gran fan de [RuboCop](https://github.com/bbatsov/rubocop) y me gustaría añadirlo a nolotiro. Normalizar el estilo de código y garantizar que lo apliquemos de manera consistente (añadiendo RuboCop a CI, o mediante algún bot que lo revise automáticamente, tipo [hound](https://github.com/houndci/hound)).

Algunos motivos. Un estilo de código conocido y consistente:

* Hace más fácil leer y entender el código.
* Da una sensación de que el código lo ha escrito una sola persona y eso crea la sensación de que todas navegamos en el mismo barco.
* Reduce posibles fricciones en las revisiones de código (es difícil tomarse de manera personal algo que te está diciendo un bot :stuck_out_tongue:).
* Facilita las revisiones de código. Por ejemplo, en el [PR 178](https://github.com/alabs/nolotiro.org/pull/178), fijaos que los cambios esenciales sólo se producen en unas pocas líneas en 2 ficheros, pero el patch incluye cambios en 8 ficheros (la mayoría de estilo). Es más fácil revisar un patch con menos verdes y menos rojos.

¿Que os parece? ¿Lo añadimos?

**Comment by andreslucena** [comment]
:+1: molaría tenerlo bien integrado al CI/github

**Comment by deivid-rodriguez** [comment]
Fixed by #193
