### ISSUE TITLE
Mejorar mensaje de error de la no confirmación

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#181]
Si un usuario no está confirmado he intenta iniciar sesión, recibe el mensaje de error “Tienes que confirmar tu cuenta para poder continuar”. No deduce que tiene que confirmar su email entrando en su cuenta de correo.

**Comment by deivid-rodriguez** [comment]
Esto ya lo mejoramos, ahora dice "Se ha enviado un mensaje con un enlace de confirmación a tu correo electrónico. Abre el enlace para activar tu cuenta.", lo cual es mucho más claro.

De todas formas, sigue habiendo un problema de usabilidad ya que el mensaje de confirmación es muy poco visible. Mi chica, por ejemplo, no lo vio y sólo pudo confirmar su registro porque se registró desde el móvil y le saltó una notificación al recibir el correo.

En general creo que los "flash messages" deberían ir lo más arriba posible en la página. Fijáos que la experience real en móvil es aún peor que en la captura que adjunto ya que el anuncio aparece más grande con lo que el mensaje queda aún más abajo.

![captura de pantalla de 2016-05-20 12 40 37](https://cloud.githubusercontent.com/assets/2887858/15425380/2b23dbe2-1e88-11e6-8647-326964aac705.png)

**Comment by andreslucena** [comment]
:+1 

relacionada con #241
