### ISSUE TITLE
Anuncios: facilitar el cambio de estado

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#182]
Que sea más facil cambiar un estado. Ahora mismo la gente no tiene claro el flujo, por lo que muchos pueden borrarla por error. 

En el mismo sitio donde esta "Edita este anuncio" deberia tener algo similar a "Cambiar a RESERVADO" o  "Cambiar a ENTREGADO".

**Comment by iokese** [comment]
Correcto. Esto facilitaría mucho la gestión de anuncios. +1

**Comment by deivid-rodriguez** [comment]
Closed via #310.
