### ISSUE TITLE
Servir assets comprimidos

### ISSUE THREAD

**Issue by apardo** [alabs/nolotiro.org#188]
<img width="857" alt="captura de pantalla 2016-04-04 a las 8 40 41" src="https://cloud.githubusercontent.com/assets/2906/14239935/f9f17e8c-fa40-11e5-9bd7-ad2bf765a785.png">

Es importante arreglar esto sobre todo para los dispositivos móviles. Comenta @deivid-rodriguez que se puede solucionar actualizando sprockets-rails.

Del lado del servidor web está todo en orden pero no sirve el .gz

**Comment by deivid-rodriguez** [comment]
Creía que habíamos arreglado esto, pero me sigue apareciendo la alerta...

/cc @apardo @andreslucena

**Comment by deivid-rodriguez** [comment]
Confirmado que ya está arreglado!
