### ISSUE TITLE
Límites texto en anuncio y comentario

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#19]
http://beta.nolotiro.org/es/woeid/779063/give
http://beta.nolotiro.org/es/ad/190056

La cantidad de texto máxima a introducir es excesiva. Revisar los límites de la versión de producción y copiarlos.

**Comment by andreslucena** [comment]
Ya está solucionado para los anuncios nuevos (o la edición de los antiguos). Comprobalo.

**Comment by iokese** [comment]
Parece que ya funciona bien, cierro.
