### ISSUE TITLE
si la url de un woeid no es del tipo town redir a  "selecciona tu localidad" , relacionada con #172

### ISSUE THREAD

**Issue by jipipayo** [alabs/nolotiro.org#191]
desde #172 ahora discriminamos correctamente los tipos de ubicación, exclusivamente de tipo localidad, en el selector de elige tu ciudad.
Ahora hay que hacer en si ponemos una url que sea de un woeid de otro tipo no nos muestre listado y no nos deje añadir regalos, se redirige a 404 o a la pagina de seleccionar tu localidad.

También impedir renderizar urls de este tipo con un string (muy lol) como woeid

https://nolotiro.org/it/woeid/7662fooooooooooooooo73/give

**Comment by jipipayo** [comment]
usar las urls de muestra que dice @deivid-rodriguez en https://github.com/alabs/nolotiro.org/issues/173#issuecomment-205457008

**Comment by deivid-rodriguez** [comment]
Por mí ok cualquiera de las opciones que propones, tanto 404 como selector. Lo digo por si 404 te resulta más fácil a nivel de implementación. Con respecto a los anuncios existentes en estas localidades "dummy", qué hacemos con ellos? Los pasamos a la ciudad principal del país? Los borramos?
