### ISSUE TITLE
Los usuarios pueden mandarse mensajes a si mismos

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#20]
Pueden ir a un anuncio y enviarse mensajesprivados, y contestarse. Deben poder comentar en sus anuncios pero no enviarse mensajes a si mismos.

**Comment by andreslucena** [comment]
Ya está solucionado. Comprobalo.

**Comment by iokese** [comment]
Ok, confirmado. De todas formas debería desaparecer la opción de enviarte un mensaje en tu perfil. http://beta.nolotiro.org/es/profile/35240 ¿no?.
