### ISSUE TITLE
Mensajería confusa

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#21]
No se si hay muchas diferencias entre las pestañas de enviado y recibido, pero confunden un poco.

Hay que pensar cómo aclarar la mensajería, quizás solo "recibidos" y "papelera. Lo ideal sería que pudieran buscar conversaciones u ordenarlas.

**Comment by andreslucena** [comment]
Ya mostramos solamente las pestañas para Recibidos y Papelería. 

Con respecto a buscar conversaciones, en principio la gema que usamos (mailboxer) lo soporta, pero hay que revisar bien si es compatible con nuestro motor de busqueda (sphinx). Al intentar de activarla parece que funciona solo con otro motor de busqueda (solr). 

Con respecto a ordenarlas, en principio eso no se puede hacer, el único orden es cronológico. Yo abríria otro ticket para la v3.1 donde trataríamos de mejoras al sistema de mensajería (como por ejemplo mejor integración con los anuncios, que también será necesario para la valoración/karma de los usuarios). Con eso se refactorizaría bastante con respecto a lo que hay ahora en la v3.

**Comment by iokese** [comment]
¿Habría alguna forma de que la fecha no fuera tan larga y ocupara 3 filas?.

**Comment by andreslucena** [comment]
Si, se me había pasado y no sabía en que ticket estaba :P 

Ya está solucioando, comprobalo.

**Comment by iokese** [comment]
ok
