### ISSUE TITLE
Revisar combinaciones de status +  tipo de anuncio

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#213]
Las siguientes urls muestran distintos listados cuando directamente no deberían existir (los anuncios de busco no tienen status).

https://nolotiro.org/es/woeid/766273/want/status/available
https://nolotiro.org/es/woeid/766273/want/status/booked
https://nolotiro.org/es/woeid/766273/want/status/delivered

**Comment by jipipayo** [comment]
bugazo si

**Comment by andreslucena** [comment]
Creo que ees porque en el formulario de busco permitimos que pongan cualquiera de esos estados. Si te fijas editando cualquier anuncio de esos se ven. 

Entiendo que no tiene nada de logica que un Ad type want tenga status. Creo que los pasos a seguir para modificar esto seria: 

- [ ] Migración de todos los Anuncios antiguos de want, quitando status o poniendo uno por defecto. 
- [ ] Revisión de estas paginas, no deberia haber /status/ para want
- [ ] Quitar opción en formulario si se cambia de tipo de Anuncio.

**Comment by deivid-rodriguez** [comment]
:+1:
