### ISSUE TITLE
Tests muy lentos

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#214]
```shell
Running via Spring preloader in process 19539
Run options: --seed 48438

# Running:

........................S..............................................S...............S......................................................................

Fabulous run in 355.630630s, 0.4443 runs/s, 1.1501 assertions/s.

158 runs, 409 assertions, 0 failures, 0 errors, 3 skips

You have skipped tests. Run with --verbose for details.
```

El problema se debe de haber introducido con https://github.com/alabs/nolotiro.org/commit/dfd5c293616847e06ebfde59cdbd7107aa64a18d y se produce porque los tests ejecutan muchas llamadas a la API de Yahoo. La soluciones por orden de más fácil (pero menos adecuadas) serían:

* Revertir el commit mencionado.
* Usar una ciudad que no sea Madrid para los tests implicados. "Madrid" sin anuncios produce unas 10 sugerencias de "Ciudades con nombres similares" cuyos woeids se resuelven posteriormente a nombres también por API. Si usáramos una ciudad con 0 sugerencias, no habría llamadas a la API.
* Usar webmock para mockear las llamadas a la API de Yahoo en los tests.
* Guardar los nombres de las ciudades en base de Datos.

**Comment by jipipayo** [comment]
me gusta mas la idea de usar una location que tenga 1o ninguna sugerencia, mas que mockearlo, si optamos por hacer una llamada al menos real, hace un test necesario que es que las llamadas a yahoo funcionan, y nos detectaria si las claves usadas son correctas, hay peticion y respuesta. etc.

También es buena la idea de ir guardando los woeids y sus correspondientes exónimos en diferentes idiomas, aunque esto lo veo mas complejo, no por los woeids si no por tener todas las posibles traducciones de las localidades en db.

**Comment by deivid-rodriguez** [comment]
Tienes razón en todo. Nos quedamos con esa opción de momento.

**Comment by deivid-rodriguez** [comment]
De todas formas, mi conexión actual va a pedales, es por eso que tardan tanto. En travis son 55 segundos. Cuando vuelva a Madrid veo cómo está el tema respecto de lo que me tardaban a mí antes.
