### ISSUE TITLE
Revisión n1: numerosos errores relacionados con cache, traducciones (i18n), alertas, contador de vistas de anuncio, token de usuario nuevo y token de algunos usuarios legacy

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#22]
Copio y pego mis notas de ayer, hay algunas que están explicadas más como código que otra cosa: 

* Falta traducciónes en el botón de las siguientes páginas: http://beta.nolotiro.org/es/ad/listall/ad_type/give http://beta.nolotiro.org/es/ad/listall/ad_type/want
* Al acceder a un anuncio no se ve el titulo correctamente en el navegador (aparece "- nolotiro"): http://beta.nolotiro.org/es/ad/190052/busco-bicicletas-no-me-inporta-su-estado  
* Al cambiar de idioma en la portada los enlaces siguen apuntando al sitio en español (/es): 
* Al ir cambiando de páginas el contador de mensajes sin leer va cambiando sin sentido. 
* Al crear un usuario no se ve la alerta de: "comprueba tu correo". Recién se ve al acceder a otra página que no sea la portada. 
* Al darle al enlace de confirmar token después de registrar un usuario dice que hubo un error al guardar el token. No se pueden crear usuarios nuevos!!. 
* En algunos mails que se envian se ve "hello" en la primer línea. 
* En la versión de producción tenemos un contador de lecturas de los anuncios que sirve para ver la popularidad de los distintos anuncios. 
* Al recibir un mail de la mensajería ponemos un enlace a la página principal. El enlace debería llevar a la conversación específica. 
* Al recibir un mail de la mensajería no queda claro que parte es el asunto y que parte el mensaje en sí. Aparece dos veces el texto de "Hay una nueva respuesta" y no queda bien. 
* En ciertos usuarios no permite iniciar sesión diciendo que no se ha confirmado la cuenta.

**Comment by andreslucena** [comment]
@iokse iba a crear varios tickets pero ya creo uno englobando a todas las cosas que encontramos ayer. 

Ya está solucionado esto y todo lo otro que hablamos ayer. Necesitaría que lo comprobases en la beta.

**Comment by iokese** [comment]
* 1 OK.
* 2 (Al acceder a un anuncio no se ve el titulo correctamente en el navegador (aparece "- nolotiro"): http://beta.nolotiro.org/es/ad/190052/busco-bicicletas-no-me-inporta-su-estado) el titulo sigue apareciendo demasiado pegado a la ciudad. Quizás se pueda aclarar bajándola más, poniéndola más grande, poniendo la fuente del enlace a la ciudad más pequeño.
* 3 OK
* 4 OK
* 5 OK
* 6 OK
* 7 OK
* 8 Falta el contador de comentarios.
* 9 Falla: Me llega un correo sin enlace al mensaje que me han mandado y en el cuerpo del correo aparece: mailboxer.message_mailer.visit_html 
* 10 OK
* 11 Antonio dice que sigue sin poder.

**Comment by andreslucena** [comment]
2. Ya está solucionado. Faltaba una regla de CSS. 
8. Ya está puesto, igual lo llevamos en el ticket #23 
9. Ya lo agregue, no se porque no se habia subido bien con los cambios ultimos. Por las dudas comprobalo tanto en un mensaje nuevo como en la respuesta a un mensaje.

**Comment by andreslucena** [comment]
11. Lo había agregado para la siguiente importación de la DDBB, igual ya subi el fix para que funcione en la beta.

**Comment by iokese** [comment]
Todo OK.
