### ISSUE TITLE
los meta description en el html renderizan mal el nombre de la localidad

### ISSUE THREAD

**Issue by jipipayo** [alabs/nolotiro.org#220]
en las etiquetas meta description de los listados de localidad se renderiza mal el nombre de la localidad,

` <meta name="description" content="regalo en {:full=&gt;&quot;Madrid, Madrid, España&quot;, :short=&gt;&quot;Madrid&quot;}. nolotiro.org es un sitio web donde regalo y busco regalos gratis de segunda mano : muebles, sillas, sofás, bicicletas, ordenadores portátiles, mesas, cocinas, lámparas, camas, ropa, juguetes, cunas o carros para bebes, teléfonos móviles y otras muchas cosas que ya no quieres y ya no necesitas para que las reutilicen otra gente a la que puede servirle o darle nueva vida." />`

**Comment by deivid-rodriguez** [comment]
Fixed via #221
