### ISSUE TITLE
Unificar página de perfil y listado de anuncios de usuario 

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#223]
Deberíamos unificar estas dos páginas. En "perfil" solo hay 2 cosas interesantes de cara al usuario: un link de enviar mensaje a este usuario y la fecha de creación de la cuenta. Debería estar todo en la misma página que el listado de anuncios, haciendo redirect a la URL buena.

**Comment by andreslucena** [comment]
Agrego screenshots de como va quedando, no me terminan de convencer los nav-pills pero esta es la idea general. Falta agregar el enlace en mi propio perfil al listado de mensajes. 

@deivid-rodriguez  que te va pareciendo? 


![seleccion_083](https://cloud.githubusercontent.com/assets/717367/14846626/019efb06-0c65-11e6-8d67-7d39b0b2305d.png)
![seleccion_082](https://cloud.githubusercontent.com/assets/717367/14846627/01cae41e-0c65-11e6-8d0e-52a2b3492b34.png)
![seleccion_081](https://cloud.githubusercontent.com/assets/717367/14846628/01cb34aa-0c65-11e6-88e8-499246a450f0.png)

**Comment by deivid-rodriguez** [comment]
@andreslucena Me gusta y desbloquea #211 así que avanti con esto!

Comments:

* Entiendo que en la página de mensajes se cambiarían los nav-pills de "disponible / reservado / entregado" por "recibido / enviado / papelera", y la barra lateral y el header del perfil se quedan igual al cambiar entre estas páginas.

* ¿Los links para cambiar entre la página de mensajes y la de anuncios se añaden a la derecha también? Otra opción sería implementar: https://github.com/alabs/nolotiro.org/issues/143, que además daría la opción de acceder al perfil (mensajes o regalos) desde cualquier lugar (muy útil desde mi punto de vista).

* Falta el link para editar el perfil propio. ¿Quizás un lapicerito a la derecha del header naranja del perfil?

* /cc @enetron para el diseño.

**Comment by andreslucena** [comment]
> Entiendo que en la página de mensajes se cambiarían los nav-pills de "disponible / reservado / entregado" por "recibido / enviado / papelera", y la barra lateral y el header del perfil se quedan igual al cambiar entre estas páginas.

Si, la idea es unificar navs/tabs lo que sea que usemos y a su vez ya aprovechar para ir migrando los elementos a bootstrap, más que nada para mejorar el responsive. Por ejemplo estos filtros de "disponible, reservado, entregado" me daban problemas en el movil (muy pequeños, sin separación) y usando los navs-* va a mejorar bastante. 

> ¿Los links para cambiar entre la página de mensajes y la de anuncios se añaden a la derecha también? Otra opción sería implementar: #143, que además daría la opción de acceder al perfil (mensajes o regalos) desde cualquier lugar (muy útil desde mi punto de vista).

Si, estaba viendo donde poner esos enlaces de ida y vuelta, otra opción (aparte de meter enlaces ahí) puede ser mejorar el header para que sea más "app 2.0" y tengas las dos principales acciones de usuario (ver perfil publico y ver mensajes privados) bien accesibles. 

> Falta el link para editar el perfil propio. ¿Quizás un lapicerito a la derecha del header naranja del perfil? 

OK, aplico esto, aparte estaba mejorando los pills para que no sean tan "bootstrap" y no rompan tanto el diseño, dentro de unas horas lo subo.

**Comment by deivid-rodriguez** [comment]
Todo lo que comentas me parece guay. Deseando ver cómo queda! :wink:

**Comment by andreslucena** [comment]
Trabajandolo en la PR #225

**Comment by iokese** [comment]
Quizás es buena idea que por defecto se listen TODOS los regalos, teniendo los enlaces par filtrar por "disponible, reservado, entregado"- El motivo es que según entras a los perfiles de usuarios que mejor gestionan la herramienta pues resulta que como cambian el estado parece que no tienen regalos. hay más motivos, también creo es bueno que haya una url con todos los regalos y que sea la principal del usuario de cara  la indexación de google.

**Comment by deivid-rodriguez** [comment]
No me parece mala idea tampoco. Propongo que al menos hasta que definamos bien y completemos #225, modifique esta PR para que muestre los filtros de esta manera:

Todos | Disponibles | Reservados | Entregados | Busco

**Comment by iokese** [comment]
+1

**Comment by deivid-rodriguez** [comment]
@iokese Estoy terminando esto y tengo algunos comentarios:

* La verdad es que no acabo de ver la necesidad de la pestaña "todos", pero si la añadimos creo que  no habría que ponerla por defecto, si no dejar "disponibles" por defecto. Hay dos casos:
  * __Cuando una usuaria visita el perfil de otra__. En este caso normalmente querrá ver regalos disponibles, no una miscelánea de anuncios. (Tu perfil de "analista" es un caso aparte pero la app debería optimizarse para las usuarias finales, no para nosotras como desarrolladoras).
  * __Cuando una usuaria visita su propio perfil__. En este caso también resulta útil ver los regalos disponibles y así tener una idea de "lo que te queda por regalar". A mí antes de introducir los filtros me resultaba incómodo ver el popurrí de regalos sin poder ordenarlos por estado.

* Por otro lado, ¿en "todos" que habría que poner? ¿Todos los regalos o todos los anuncios? Todos los anuncios, incluyendo "busco", ¿no?

**Comment by iokese** [comment]
Quizás no lo definiría como una pestaña extra, sino que al entrar vieran todos pero pudiera filtrarlos con las otras opciones. Quizás se pueda poner aparte el número de regalos que tiene en manera numérica bien visible en el perfil, sin tener que entrar a contarlos. Algo así como unos contadores.

**Comment by deivid-rodriguez** [comment]
> Quizás no lo definiría como una pestaña extra, sino que al entrar vieran todos pero pudiera filtrarlos con las otras opciones.

Mmmmm, entiendo la idea de añadir unos filtros un poco más avanzados en el futuro, pero de momento creo que habría que arreglar las pestañas simplemente. Aunque no me convenza lo de la pestaña "todos", de momento la añado como pestaña por defecto, que ya es una mejora sobre lo que tenemos ahora.

> Quizás se pueda poner aparte el número de regalos que tiene en manera numérica bien visible en el perfil, sin tener que entrar a contarlos. Algo así como unos contadores.

Si queréis puedo poner el contador de anuncios entre paréntesis en cada pestaña.

**Comment by deivid-rodriguez** [comment]
He modificado #211 añadiendo un tab "Todos" de momento, que agrupa todos los regalos de la usuaria. Queda así:

![captura de pantalla de 2016-05-29 08 21 42](https://cloud.githubusercontent.com/assets/2887858/15632939/246dc48e-2577-11e6-8974-9314d8892bd7.png)

**Comment by iokese** [comment]
Hay que dejar espacio para la foto del perfil. La idea origina de Andrés estaba bien encaminada, pero es un tema de diseño que debe esperar a la propuesta final.

**Comment by deivid-rodriguez** [comment]
Sí, no me olvidado de esto y de la PR de @andreslucena (#225), de hecho la he rebasado hace poco para actualizarla el código actual.

Pero el tema es eso, mejor esperar al nuevo diseño y ver ahí cómo lo incorporamos.

**Comment by deivid-rodriguez** [comment]
Fixed by #225. Closing.
