### ISSUE TITLE
Líneas texto anuncio más cortas

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#24]
Quizás sería bueno que las líneas del contenido de un anuncio no superaran los 150 caracteres o menos, para que no sean tan largas y se metan debajo de las fotos.

**Comment by andreslucena** [comment]
Ya está subido, revisarlo. Lo dejé en 200 caracteres, con separación con " " (para que no corte las palabras). Creo que así ya son pocas palabras, entrarían 250. Como lo ves?

**Comment by iokese** [comment]
Las líneas siguen siendo muy largas, dificultan la lectura. Creo que habría que bajarlo a 100.

**Comment by iokese** [comment]
Espera, que comparando con la versión en producción está bien...

**Comment by andreslucena** [comment]
Vale. Es que si son más cortas todavía no se va a leer nada en la portada. Yo lo dejaría tal como está ahora mismo de momento y ya vemos cuando pasemos esto a producción si lo ajustamos un poco más.
