### ISSUE TITLE
Mejorar menu principal en móvil

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#241]
Ahora mismo hay que hilar muy muy fino para poder hacer click desde móvil en el icono de mensajes por ser minúsculo. Además, no deja hacer zoom. Ahora mismo lo normal es no acertar y acabar clickando el link de "nolotiro.org - Madrid, Madrid, España". Hay que hacer esto más amigable.

![captura de pantalla de 2016-05-20 13 16 19](https://cloud.githubusercontent.com/assets/2887858/15426231/83e727f2-1e8d-11e6-8bda-976167331f8d.png)

**Comment by deivid-rodriguez** [comment]
Esto es HIGH priority, me parece.

**Comment by andreslucena** [comment]
:+1 hay que refactorizar el header en movil que no se llega a hacer click
