### ISSUE TITLE
Adsense: en mensajería

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#25]
Apareen debajo, en formato pequeño y no al lado en formato cuadrado.

**Comment by andreslucena** [comment]
Relacionada con #14

**Comment by franciscout** [comment]
Ya hay ads en el thread de messages (es/messages/xxxxx), revisar y cerrar.

**Comment by iokese** [comment]
No lo cierro por que el AD está pisando todo el footer, ciérralo tu si lo ves claro.

**Comment by andreslucena** [comment]
Efectivamente el ad esta roto, ya lo esta revisando @franciscout

**Comment by franciscout** [comment]
Ya no deberia crear conflictos, haya anuncios en la lista o este vacia; revisar y cerrar?

**Comment by iokese** [comment]
Sigue sin ser el banner cuadrado, lo que aparece es uno alargado, hay que dejar el cuadrado que hay en producción,

**Comment by franciscout** [comment]
(lo cerre por error al poner el 'fix' en el ultimo commit)

Ya hice el cambio, revisalo cuando puedas.

**Comment by iokese** [comment]
El banner no tiene el mismo tamaño que el de producción, hay que dejar exactamente el mismo.

**Comment by franciscout** [comment]
Creo que ya esta, que faltaria?

**Comment by iokese** [comment]
Dentro de cada mensaje el banner sigue sin funcionar.

**Comment by franciscout** [comment]
No entendi esto ultimo... te refieres al google_ad dentro de /messages/xxxxx, no?

Ahora mismo estoy revisando ese, dentro de cada thread de mensajes entre los diferentes usuarios, en desktop yo creo que ya esta OK y estoy preparandolo en responsive.

**Comment by iokese** [comment]
Si, me refiero a eso. A mi no me sale bien, mira como sale en la imagen que adjunto.
![captura de pantalla de 2015-05-18 10 05 36](https://cloud.githubusercontent.com/assets/1123486/7683555/807ce7ba-fd45-11e4-9223-88fe2f351639.png)

**Comment by franciscout** [comment]
Habria que revisar, por ahora encontre un bug entre las resoluciones 700-850. 
Mira a ver si encuentras mas.

**Comment by franciscout** [comment]
Este tambien creo que ya esta para cerrar, @iokese ??

**Comment by iokese** [comment]
En cuanto se vuelvan a ver por mi parte se puede cerrar, pero ahora no se ve ninguno.

**Comment by franciscout** [comment]
Consigues ver anuncios en alguna parte de la pagina o no aparecen solo en paginas particulares? (estilo #62 / #50 ?)

**Comment by iokese** [comment]
Ya lo veo todo, cierro.
