### ISSUE TITLE
Adsense: en ficha de anuncio de regalo

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#26]
http://beta.nolotiro.org/es/ad/189368/se-regala-gatito-de-15-dias

El ad es demasiado grande y tapa la parte de abajo.

**Comment by andreslucena** [comment]
Relacionada con #14

**Comment by franciscout** [comment]
Ya esta solucionado, revisar y cerrar :)

**Comment by iokese** [comment]
No queda bien ya que ahora aparece muy pequeño, pero lo cierro y abro otra.
