### ISSUE TITLE
Añadir un nuevo estado "expirado"

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#269]
Hacer que los anuncios caduquen después de un cierto tiempo. Los anuncios se marcarían en la UI de una manera distinta (en gris, como "expirado" o "caducado", por ejemplo), si es que decidiéramos listaros (por ejemplos, los que ya están, por compatibilidad hacia atrás con los bots de google).

Esto resuelve el problema que sale a veces de "Qué hacemos con los anuncios viejos"?

* Por un lado, nos permite no perder el contenido ya indexado en google que se perdería si simplemente borramos los anuncios antiguos y nos evita falsos positivos (con las reglas actuales no hay ningún motivo para no tener un anuncio publicado y disposible durante un periodo muy largo, con lo que tampoco debemos borrar el contenido de las usuarias sin avisar).
* Por otro, dejamos de generar "falsas expectativas" al tener muchos anuncios disponibles que no están disponibles, sino para los que la usuaria nunca cambió el estado.

El plan sería:

- [ ] Migrar todos los anuncios antiguos (posiblemente mandando mail a las usuarias antes).
- [ ] Decidir un período de expiración por defecto (1 mes?) y hacerlo configurable en el formulario de creación / edición de anuncio. (#237).
- [ ] Añadir workers que expiren automáticamente los anuncios.
- [ ] Adaptar el diseño (nueva etiqueta "expirado / caducado").
- [ ] Decidir si añadimos listados de anuncios expirados (no sé si tiene mucho sentido).

**Comment by erm3nda** [comment]
> por ejemplos, los que ya están, por compatibilidad hacia atrás con los bots de google

No perder visitas está bien, sin embargo quien entre desde google (aunque no lo listes en la web by default) verá el anuncio y lo mismo piense que está ok, cuando no lo está.

Tal vez puedes simplemente meter una redirección 310L permanente a portada, un anuncio sobre anuncios expirados, y un listado que presente contenido similar al link que se puso, sin llegar a renunciar ese anuncio. (Desconozco las artimañas de Google, sólo sé que son un poco putas y que realmente no conozco las consecuencias, pero hasta donde leí en su día la 301 resuelve OK por su parte y no penaliza, claro que como cada vez sacan un panda o una iguana con reglas nuevas... sólo lo pongo como sugerencia.)

Ejemplo, "ops, este anuncio es más viejo que Matusalén, tal vez prefieres ver anuncios más frescos", y le petas justo debajo la nueva lista con contenido similar.

> Decidir un período de expiración por defecto (1 mes?) y hacerlo configurable en el formulario de creación / edición de anuncio. (#237).

Y que refresque la fecha al renovar, que renovar no sea tedioso, que sería la contraparte de "no borrar". Algo relajado pero que no permita anuncios de hace 3 años. Hasta la vista, un rango de 3 meses es auténtico, hay cosas que llevan ese tiempo y aún están listadas. 6 meses ya roza el "uy no se donde lo puse", "lo he tirado", etc.

> Añadir workers que expiren automáticamente los anuncios.

Con un cron va que chuta. Y si la web tiene al menos 1 visita semana (obvio que si, y cada minuto...) pues una limpieza semanal puede ser suficiente. Cada semana una visita (nocturna a poder ser) hará de trigger para la funcion de cleanup que se hará sutilmente :D

Cuando leo worker, sobreentiendo un proceso auxiliar que está ahí haciendo nada 24/7 cuando en realidad con un cron cada semana puede ser suficiente. (desconozco el volumen de anuncios a limpiar, pero seguro que cuando esté en marcha serán menos que en el firstrun)

> Decidir si añadimos listados de anuncios expirados (no sé si tiene mucho sentido).

Yo lo haría y lo llamaría Histórico. Con un link que ponga ,cosas y cosas y cosas, cualquier cosa que no quieras, nolotiro y que se inflen a ver ejemplos de cosas que se han regalado... Así por el otro lado mantienes la URL de Google.

Saludos.

**Comment by deivid-rodriguez** [comment]
> No perder visitas está bien, sin embargo quien entre desde google (aunque no lo listes en la web by default) verá el anuncio y lo mismo piense que está ok, cuando no lo está.

La idea es que el estado expirado quedé clarísimo. Sin links para contactar, en gris, etc.

> Tal vez puedes simplemente meter una redirección 310L permanente a portada, un anuncio sobre anuncios expirados, y un listado que presente contenido similar al link que se puso, sin llegar a renunciar ese anuncio. (Desconozco las artimañas de Google, sólo sé que son un poco putas y que realmente no conozco las consecuencias, pero hasta donde leí en su día la 301 resuelve OK por su parte y no penaliza, claro que como cada vez sacan un panda o una iguana con reglas nuevas... sólo lo pongo como sugerencia.)

> Ejemplo, "ops, este anuncio es más viejo que Matusalén, tal vez prefieres ver anuncios más frescos", y le petas justo debajo la nueva lista con contenido similar.

Si, todo esto hay que mirarlo, pero de momento no me preocupa mucho. Me refiero, con quitar los anuncios expirados del listado por defecto y ponerlos en gris en otro lugar nos vale. Luego ya nos pegamos con google pero de momento eliminamos las falsas expectativas.

> Y que refresque la fecha al renovar, que renovar no sea tedioso, que sería la contraparte de "no borrar". Algo relajado pero que no permita anuncios de hace 3 años. Hasta la vista, un rango de 3 meses es auténtico, hay cosas que llevan ese tiempo y aún están listadas. 6 meses ya roza el "uy no se donde lo puse", "lo he tirado", etc.

Si, lo de renovar ya lo tenemos implementado. Es "Republicar", simplemente refresca la fecha y lo pone como disponible.

> Con un cron va que chuta. Y si la web tiene al menos 1 visita semana (obvio que si, y cada minuto...) pues una limpieza semanal puede ser suficiente. Cada semana una visita (nocturna a poder ser) hará de trigger para la funcion de cleanup que se hará sutilmente :D

> Cuando leo worker, sobreentiendo un proceso auxiliar que está ahí haciendo nada 24/7 cuando en realidad con un cron cada semana puede ser suficiente. (desconozco el volumen de anuncios a limpiar, pero seguro que cuando esté en marcha serán menos que en el firstrun)

Puede ser vía cron "estático" (en plan una vez por semana) o algo un poco más sofisticado, en plan encolar la tarea de expiración cuando se (re)publica el anuncio para 3 meses después (o la fecha que haya especificado el usuario). El tema cron vs worker no es un problema. Los workers de `sidekiq`, el motor de procesos asíncronos que usaríamos, están ahí sin ociosos sin consumir recursos cuando no tienen trabajo. No molestan.

> Yo lo haría y lo llamaría Histórico. Con un link que ponga ,cosas y cosas y cosas, cualquier cosa que no quieras, nolotiro y que se inflen a ver ejemplos de cosas que se han regalado... Así por el otro lado mantienes la URL de Google.

Relacionado con el primer párrafo, me parece guay y nos simplifica el trabajo. :+1:
