### ISSUE TITLE
Error confuso al meter capcha

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#27]
"1 error prohibieron que se guardase este anuncio:

    Hubo un error con los caracteres que tenias que poner por seguridad, vuelve a rellenar las letras que veas (el captcha)"

Es confuso, habría que poner algo como: "Posiblemente has introducido mal los caracteres del captcha ya que no coindicen con la imagen, vuelve a introducirlos". o algo que sea más claro.

**Comment by andreslucena** [comment]
Hecho y en beta.

**Comment by iokese** [comment]
ok
