### ISSUE TITLE
Adsense: en el listado de anuncios (página de ciudad)

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#28]

**Comment by andreslucena** [comment]
Relacionada con #14

**Comment by franciscout** [comment]
Casi todo hecho, hay que revisar buscando por resoluciones que queden mal, si alguien encuentra alguna que la ponga.

**Comment by iokese** [comment]
En producción teníamos 2 anuncios en la página de ciudad, falta 1.

**Comment by franciscout** [comment]
Ya corregí y puse dos anuncios verticales a la derecha en la pagina de ciudades, lo ves bien??

**Comment by iokese** [comment]
Si, se ve correcto, cierro el ticket.
