### ISSUE TITLE
Borrar anuncios también al bloquear usuario

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#286]
Añadir esto al link de "Bloquear usuario" nos quitaría mucho trabajo de moderación, no?

**Comment by deivid-rodriguez** [comment]
Creo además que resolviendo esto podemos cerrar también #85 ya que sería innecesario.

**Comment by iokese** [comment]
+1

**Comment by deivid-rodriguez** [comment]
Al final vamos a añadirlo como un nuevo link "Bloquear usuario (y borrar anuncios)"

**Comment by deivid-rodriguez** [comment]
Esto al final no se ha hecho. No borramos anuncios automáticamente ya que nos interesa conocer el tipo de contenido inapropiado que recibimos para poder estudiarlo y prevenirlo.

La solución actual para esto es que, cuando bloqueamos a un usuario, automáticamente todos sus anuncios dejan de mostrarse en la web.

Fixed by 4c44f8e2e4c76126384a2cb6f13381e08b245e0f.
