### ISSUE TITLE
Imagenes de post demasiado altas

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#29]
Las imágenes de los post aparecen demasiado arriba, tanto en el listado de ciudad como al visualizar el anuncio. Hay que bajarlo un poco.

**Comment by andreslucena** [comment]
¿Están al mismo tamaño que en producción actualmente, no?

**Comment by iokese** [comment]
Si, creo que deberá ir unos pixel más abajo pero no es imprescindible, mejor lo cierro.
