### ISSUE TITLE
Actualizar info de páginas:

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#30]
http://beta.nolotiro.org/es/page/about (actualizar el software con el que funciona nolotiro y enlace a github).

En el footer de todas las páginas: El enlace al github.

Formulario de contacto: http://beta.nolotiro.org/es/contact  aparece en inglés. Si el usuario está logueado no debería pedirle su email sino tomar sus datos automáticamente (ni siquiera pedirle que lo rellene, ni que lo vea, que aparezca solo el campo "asunto" y el cuerpo del mensaje.

**Comment by andreslucena** [comment]
Ya está hecho lo del mail automaticamente, los enlaces a github, el software en el que funciona nolotrio. 

Creo que lo único que falta es lo de la traducción del inglés.

**Comment by andreslucena** [comment]
Ya está hecha la traducción al inglés. Falta revisar todo y cerrar el ticket.

**Comment by iokese** [comment]
Aún sigue pidiendo el campo "Tu email".

**Comment by andreslucena** [comment]
Te sigue pidiendo el campo cuando no iniciaste sesión. Una vez iniciaste sesión ya no te lo pide. ¿No era eso lo que pedías?

**Comment by iokese** [comment]
Perfecto, lo cierro.
