### ISSUE TITLE
Hay usernames duplicados en DB

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#300]
Cambios recientes han hecho que se manifieste este bug (https://err.nolotiro.org/apps/571de5807a440000b2000005/problems/57620c149b4cb1011e000001). Habría que:

* Cambiar los datos inválidos para que los usernames sean únicos.
* Añadir un índice único en DB para asegurar la integridad futura de los datos.

**Comment by deivid-rodriguez** [comment]
Eso, o eliminar la restricción de unicidad del modelo como ya he hecho con la longitud en #297. @andreslucena ?

**Comment by andreslucena** [comment]
Creo que no deberiamos sacar esa restricción, asi podemos ponerlo como URL (amigable). Lo que me entran dudas es si deberiamos permitir que cambien de username a posteriori (despues de registrarse).

**Comment by deivid-rodriguez** [comment]
> Creo que no deberiamos sacar esa restricción, asi podemos ponerlo como URL (amigable).

Cierto, no se me había ocurrido. Para arreglar los datos inválidos propongo, por ejemplo, cambiar a `"#{nombre antiguo} nolotiro"` al duplicado que tenga menos anuncios.

> Lo que me entran dudas es si deberiamos permitir que cambien de username a posteriori (despues de registrarse).

Yo diría de permitirlo, de hecho lo propuse en #240.

**Comment by deivid-rodriguez** [comment]
No parece que haya muchos casos, creo que se puede arreglar a mano:

```
irb(main):010:0> PP.pp User.select(:email, :username).group(:username).having("count(*) > 1").size
   (0.4ms)  SELECT COUNT(*) AS count_all, username AS username FROM `users` GROUP BY `users`.`username` HAVING count(*) > 1
{""=>3,
 "Aldana Delgado Berrocal"=>2,
 "Ana Tapia"=>2,
 "Anisley Sarmiento Caminero"=>4,
 "B"=>2,
 "Bego"=>5,
 "Bel"=>3,
 "Ben"=>2,
 "Carlos Jimenez"=>2,
 "Cuba"=>2,
 "Danilo Jacobs"=>2,
 "Emilio Lopez"=>2,
 "F"=>3,
 "I"=>2,
 "Irene Diaz"=>2,
 "Isa"=>2,
 "Ivonne"=>2,
 "Jose Manuel"=>2,
 "Juan Doe"=>2,
 "Lilia Butnaru"=>2,
 "Luc"=>4,
 "M"=>13,
 "Madrile"=>3,
 "Malague"=>2,
 "Manu Santos"=>2,
 "Mar"=>13,
 "Marlene"=>2,
 "María José "=>2,
 "Mercedes Gonzalez"=>2,
 "Miguel "=>2,
 "Miguel Angel"=>2,
 "Nacho"=>2,
 "Ni"=>2,
 "Patricia Gonzalez"=>2,
 "Ra"=>2,
 "Rafa"=>2,
 "Robben Cepeda"=>2,
 "Rocio Sanchez"=>2,
 "Sara Gimenez"=>2,
 "To"=>2,
 "V"=>2,
 "Valentina Migliarini"=>2,
 "Victoria Negro"=>2,
 "anto"=>2,
 "bego"=>3,
 "i"=>2,
 "jorge gomez"=>2,
 "luisi"=>3,
 "m"=>6,
 "madrile"=>3,
 "mar"=>2,
 "to"=>3,
 "yoli"=>2}
```

**Comment by deivid-rodriguez** [comment]
Fixed by #370.
