### ISSUE TITLE
Error ingles al subir foto

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#31]
Cuando subes un fichero que no debes (en este caso un mp4) me ha salido el siguiente errormedio ingles y español:
"4 errors prohibieron que se guardase este anuncio:

    Image content type no es válido
    Imagen del anuncio no es válido
    Imagen del anuncio debe estar entre 0 Bytes y 1 MB
    Image file size debe estar entre 0 Bytes y 1 MB"

Hay que quitar los errores en ingles y aclarar los mensajes en español. Aparte de eso, sería bueno revisar que en general los mensajes de error no comiencen nunca por "4 errors prohibieron", debe ser algo más sencillo y amable como: "Hay un problema, revisa esto:" o similar.

**Comment by andreslucena** [comment]
Ya está subido el cambio, falta revisarlo.

**Comment by iokese** [comment]
Perfecto.
