### ISSUE TITLE
Texto en Ingles al modificar anuncio

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#32]
"Ad was successfully updated."

**Comment by andreslucena** [comment]
Ya está cambiado, revisarlo.

**Comment by iokese** [comment]
Al editarlo y meter meter el título más largo sale en inglés:
"Hay un problema, revisa esto:

    Title es demasiado largo (100 caracteres máximo)"

Revisar también esto al poner u anuncio normal (no al editarlo).

**Comment by andreslucena** [comment]
Hecho y solucionado. Por cierto, ya no te tendría que dejar reproducir ese error por #43 - podrías probar con el limite inferior (necesita un minimo de 10 caracteres).

**Comment by iokese** [comment]
Todo ok.
