### ISSUE TITLE
Modificaciones en "ayuda a traducir"

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#33]
http://beta.nolotiro.org/es/page/translate

No debería aparecer un link de "volver a la página de inicio", y el enlace a "ayudanos a traducir al tuyo" debería estar dentro del cuadro  y más visible.

**Comment by andreslucena** [comment]
Vale, ya quité el enlace y puse un recuadro en lo de ayudanos a traducir. Revisalo y decime si metemos algo más que hay muy poco texto.

**Comment by iokese** [comment]
El texto está bien, quizás ponerlo un poco más grande para que se vea mejor.

**Comment by andreslucena** [comment]
Bueno, de momento lo dejaré así que tampoco quiero estar cambiando el diseño (esta versión tiene que ser lo más similar posible a lo que hay ahora en producción). Cierro el ticket.
