### ISSUE TITLE
Herramienta de traducción

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#34]
Es muy confusa, hablemos.

**Comment by andreslucena** [comment]
¿Te parece mejor transifex o se te ocurre alguna alternativa? En más sencillo todo si es un servicio externo.

**Comment by iokese** [comment]
El problema es cómo te presenta las cadenas. Dice que algunas están en Español pero están en inglés y cuando estás traduciendo de otra lengua eso hace que no esté claro. No se si es un problema de la herramienta ino de la traducción de nuestras cadenas.

**Comment by andreslucena** [comment]
¿Cuales son las cadenas que aparecen en inglés? Pasame algunas.

**Comment by iokese** [comment]
https://accounts.localeapp.com/projects/6872/translations?in_locale=20644&state=incomplete

**Comment by andreslucena** [comment]
OK, parece que el tema está de mi lado, efectivamente son traducciones que faltan. Las agrego y te aviso.

**Comment by andreslucena** [comment]
Vale, efectivamente se trataba de traducciones que faltaban por mi parte o que al herramienta detectaba que faltaban pero porque en español no existe ese concepto (localizacion con distintos tipos de unidades). 

Con esto tenemos el castellano al 100%, la URL que está más arriba ya no funciona (redirige al catalan) así que  creo que está todo bien. Como ya estamos al 100% cierro el ticket. 

Lo único que me genera dudas es que creo por como funciona esto (localeapp) tendríamos que tocar desde un lado solamente para el caso del "es" (por la sincronización que hay de push/pull). 
En principio los dos lados de los que hablo son localeapp y github (nuestro repositorio git). A mi lo que me resulta más cómodo es hacerlo en git, por lo que si queres cambiar algún texto para el "es" lo mejor es hacerlo aquí: 
https://github.com/alabs/nolotiro.org/blob/master/config/locales/es.yml
Y para el resto de idiomas si vamos a usar localeapp.
