### ISSUE TITLE
Añadir rankings de usuarias por ciudad

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#348]
<strike>En el espacio dejado por #342.</strike> Nada que ver con #342, eso es en el listado de la usuaria, esto es en el listado de la ciudad.

**Comment by iokese** [comment]
¿Que pasa con las ciudades donde no hay actividad?, ¿lo dejamos en blanco?.

**Comment by deivid-rodriguez** [comment]
Yo diría que sí. Entiendo que el banner se mantiene pero debajo del ranking no?

**Comment by iokese** [comment]
Correcto.
