### ISSUE TITLE
Control login

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#35]
Cuando un usuario mete su clave 3 veces mal se le pide un captcha

**Comment by andreslucena** [comment]
Lo más simple con respecto a esto es bloquear al usuario a la X cantidad de intentos fallidos de inicio de sesión durante Y días. Esto ya lo trae la librería que usamos para el acceso de los usuarios. Habría que decidir cuantos intentos fallidos. 

Yo creo que a los 10 intentos fallidos y que bloquee al usuario durante 3 horas estaría bien. ¿Como lo ven?

**Comment by iokese** [comment]
+1

**Comment by andreslucena** [comment]
Hecho, faltaría revisar (prueba con el mail de algun usuario cualquiera, debería cambiar el mensaje al intento fallido numero 11).

**Comment by iokese** [comment]
Lo intenté más de 15 veces y no pasó nada distinto.

**Comment by andreslucena** [comment]
Me faltaba activar más cosas para que funcionase. Ya está en la beta.

**Comment by iokese** [comment]
oK, ahora SI la bloquea. ¿Cuanto tiempo pasa hasta que peude entrar?.
El mensaje al usuario no explica cuanto tiempo falta para que pueda entrar de nuevo.

**Comment by andreslucena** [comment]
Ya lo puse en los textos, son estos: 

+      last_attempt: Ten cuidado que si sigues intentando te bloquearemos la cuenta por 3 horas. ¿Has olvidado tu contraseña? Recuperala.
+      locked: Tu cuenta está bloqueada. Puedes volver a acceder dentro de 3 horas.

**Comment by iokese** [comment]
Ok.
