### ISSUE TITLE
Eliminar "Comentarios"?

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#377]
Hace tiempo si me pregunto si necesitamos los comentarios.

Como motivos para eliminarlos, veo:
- El flag de "permitir comentarios públicos" es _confuso_ (#186), y el email de notificación también porque es muy similar al de mensaje privado.
- La feature, entiendo originalmente pensada para aclaraciones sobre el regalo, al final casi siempre se usa para lo mismo que los mensajes privados: _pedir el regalo_, con lo que no aporta nada al resto de usuarias.
- Es un punto de _complejidad_ y de moderación extra. Por ejemplo, la gente publica mucho el número de teléfono aquí.
- Eliminarlos alivia la "carga de trabajo" para los regaladores. Para aclaraciones públicas siempre se puede editar el anuncio.
- Podemos sustituir los comentarios por una nueva sección de "Agradecimientos", "Foro" o lo que decidamos.
- En el futuro me gustaría subtituir el contador de comentarios por uno de "candidaturas" (el número de personas interesadas en el regalo), que es algo más útil para el resto de usuarios

**Comment by iokese** [comment]
Algunos argumentos en otra dirección:
* También se usan los comentarios para denunciar anuncios estafa, SPAM, o malas actitudes de usuarios. 
* Es uno de los pocos espacios para generar comunidad, a veces se hablan y apoyan por ahí creando comunidad o enlace entre personas.
* Un foro es algo que suele costar más tiempo de mantenimiento (un nuevo servicio en los servidores a actualizar cada X tiempo, moderación extra que se sale del acto de regalar).
* Por defecto está deshabilitado, por lo que no creo que genere mucha cara para los regaladores salvo que ellos quieran dar esa posibilidad.
Sí estoy muy de acuerdo con el último punto (cambio de contador de comentarios por candidaturas) donde el candidato pueda dar en 250 caracteres un motivo por el que lo quiere.
De momento dejaría los comentarios, ojalá con el filtro "antiteléfono", para que puedan seguir hablando. Ya verás el ejemplo en navidad, en ese mes se hablan y felicitan mucho por los comentarios.

Mis 2 cent.

**Comment by deivid-rodriguez** [comment]
> También se usan los comentarios para denunciar anuncios estafa, SPAM, o malas actitudes de usuarios. 

De acuerdo en que en ningún caso deberíamos eliminarlos hasta que no tengamos herramientas sustitutivas para hacer estas cosas.

> Es uno de los pocos espacios para generar comunidad, a veces se hablan y apoyan por ahí creando comunidad o enlace entre personas.

De acuerdo. En ese caso, mantendría los comentarios, pero en la nueva sección de "foro", "agradecimientos" o el scope que le demos.

> Un foro es algo que suele costar más tiempo de mantenimiento (un nuevo servicio en los servidores a actualizar cada X tiempo, moderación extra que se sale del acto de regalar).

En este caso sólo es un nuevo tipo de anuncio. No hay mantenimiento extra. Lo moderación, la misma, o menos porque se canalizarán automáticamente anuncios que ahora la gente publica en regalo porque no tienen cabida en otro lugar.

> Por defecto está deshabilitado, por lo que no creo que genere mucha cara para los regaladores salvo que ellos quieran dar esa posibilidad. Sí estoy muy de acuerdo con el último punto (cambio de contador de comentarios por candidaturas) donde el candidato pueda dar en 250 caracteres un motivo por el que lo quiere. De momento dejaría los comentarios, ojalá con el filtro "antiteléfono", para que puedan seguir hablando. Ya verás el ejemplo en navidad, en ese mes se hablan y felicitan mucho por los comentarios.

Está deshabilitado pero mucha gente creo que lo habilita porque no entiende bien la opción y cree que si no no les van a poder escribir o algo. De todas formas, ya tenemos un ticket para mejorar eso: https://github.com/alabs/nolotiro.org/issues/186.

El punto de lo de candidaturas no lo he explicado bien. En la nueva mensajería ciertas conversaciones estarán vinculadas a un regalo (las que se inicien a través del link "Enviar un mensaje privado al anunciante" de un anuncio). De este modo, podremos saber el número de "candidatos" a un regalo (el número de personas que han contactado a un regalador para pedirle el regalo). Me parece interesante mostrar este contador, así la gente puede descartar pedir regalos porque los haya pedido ya mucha gente y se alivia un poco de carga al regalador.

Mi conclusión es: _Ahora no, pero reevaluémoslo en un futuro_

**Comment by abelkuest** [comment]
Estoy a favor de mantener los comentarios publicos, sin embargo, creo que a veces, los comentarios llevan confusión con mensaje privado (dado que  escribir comentario es muy facil pero para enviar un mensaje interno necesitas buscar mas). Otra cosa muy importante es permitir que la gente pueda eliminar comentarios escritos

**Comment by mijailr** [comment]
Related to #646
