### ISSUE TITLE
Fallo refresco contador lecturas

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#38]
En la página de ciudad no se actualizan
Comparar las lecturas del primer anuncio http://beta.nolotiro.org/es/woeid/766273/give con las lecturas del propio anuncio: http://beta.nolotiro.org/es/ad/190059/impresora-3d-loca

**Comment by andreslucena** [comment]
Eso es lo que decía que pasa con el tema de la cache. Si refresco ese número en todas las páginas la web puede ir mucho más lenta.

**Comment by andreslucena** [comment]
Ya está solucionado lo del refresco del contador de lecturas. Lo he quitado de la cache.

**Comment by iokese** [comment]
Perfecto
