### ISSUE TITLE
Falta el numerador de páginas

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#40]
Poner un numerador de páginas pequeño y sencillo debajo de "<- atrás - siguiente ->"

**Comment by andreslucena** [comment]
Ya está subido a la beta. Revisalo.

**Comment by iokese** [comment]
"Siguiente" debería tener la misma forma que "atrás", ¿no?.

**Comment by iokese** [comment]
Quizás ambos deberían estar fuera del cuadrito.

**Comment by andreslucena** [comment]
El diseño cambia de siguiente/atras porque atras está desactivado (en gris). 

La verdad que no me liaría mucho más con todo lo que sea diseño, sino que lo dejaría pendiente para la v4/v5 con Material design, VR o lo que esté de moda en ese momento :P

**Comment by iokese** [comment]
ok
