### ISSUE TITLE
Que el 1º mensaje privado a un anuncio no pueda incluir teléfono

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#42]
Muchos usuarios "agobian" a otros contestando a todo y dando el teléfono para que les llamen o les atiendan por ese canal. Quienes reciben esos mensajes se quejan del agobio y del coste que puede tener para ellos, aparte de que abandonan la herramienta.
Es necesario que se puedan pasar el teléfono si quieren para poder organizarse, pero en el 1º mensaje que le envías a un usuario no es necesario, y evitaría acciones que agobien a los usuarios.

**Comment by andreslucena** [comment]
Creo que el problema de fondo en realidad está más relacionado con Karma: dados muchos mensajes recibidos de distintos usuarios, no es facil poder decir que usuario es el que tiene más regalos dados/puntuación general para saber quien es "mejor" (en el contexto de la app). Esta relacionado con esto: 

http://nolotiro.uservoice.com/forums/30282-espa%C3%B1ol/suggestions/1203839-poder-dar-nota-a-los-usuarios
http://nolotiro.uservoice.com/forums/30282-espa%C3%B1ol/suggestions/1342393-dar-privilegios-al-que-da-que-al-que-no-da

Preferiría que nos centrasemos ya en ese flow que lo del bloqueo de numeros es facil saltarlo (ejemplo si pongo 612345678 me lo bloquea pero si pongo 6 uno 2345678 o 6-1-2345678 o seis uno ... no lo bloquea).

**Comment by iokese** [comment]
ok, cierro.
