### ISSUE TITLE
No poder escribir más de 500 caracteres en regalo (antes de guardar).

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#43]
Que no te permita seguir escribiendo, porque si no la gente mete más y luego tiene que ir borrando hasta acertar. Es más sencillo que no puedan escribir más, y que les aparezca un mensaje diciendo que han superado los 500 caracteres.

**Comment by andreslucena** [comment]
Ya está solucionado con una propiedad de HTML5 (maxlength). La movida es que deja de permitir escribir más caracteres y no mostramos el contador hacia atrás. Para que quede más claro puse el mensaje de "limite X caracteres" para que quede un poco más claro. 

Como solución final no me termina de convencer, pero lo mismo que antes, de momento lo dejaría así pendiente para un rediseño general (los formularios no tienen practicamente nada de diseño asociado).

**Comment by iokese** [comment]
ok
