### ISSUE TITLE
Publicar en busco lleva apublicar regalo

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#44]
Cuando estás en "Busco", y le das a añadir nuevo "busco", te lleva al formulario para publicar el anuncio pero con la opción "Regalo" activad. Eso lleva a que muchos "busco" acaben en regalo por error, muy pesado para los usuarios y para la moderación.

Cambiar a: Al estar en "Busco" y quieren publicar un "busco" lleve al formulario pero con la opción "busco" activada por defecto.

**Comment by andreslucena** [comment]
Ya está arreglado, cuando se está en busco o en un anuncio de busco y se le da a publicar ya publica en esa categoria.

**Comment by iokese** [comment]
ok.
