### ISSUE TITLE
Mejorar flujo de republicación

### ISSUE THREAD

**Issue by deivid-rodriguez** [alabs/nolotiro.org#458]
Actualmente el link de "Republicar anuncio" aparece en todos los "status" de anuncio, y lo único que hace es actualizar la fecha de publicación. Creo que podemos hacer el flujo un poco más amigable. Propongo esto:
- **Para peticiones**, igual que ahora.
- **Para regalos disponibles**, igual que ahora.
- **Para regalos reservados**, actualiza la fecha de publicación como ahora pero además marca el anuncio como disponible.
- **Para regalos entregados**, no aparece el link. No se pueden republicar anuncios entregados.

\cc @andreslucena @iokese @enetron

**Comment by iokese** [comment]
+1
