### ISSUE TITLE
Puedes agregarte a ti mismo como amigo.

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#46]
No tiene sentido, mejor quitarlo, pero que puedas seguir añadiendo a otros.

**Comment by iokese** [comment]
Además, al intentar borrarte a ti mismo de tu lista de amigos te manda a la página de error.

**Comment by andreslucena** [comment]
Solucionado, falta comprobar que no aparezca más el enlace.

**Comment by iokese** [comment]
ok
