### ISSUE TITLE
Paginación en los mensajes privados

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#47]
Hay usuarios con cientos de mensajes privados, no puede salir todo en una pantalla.

**Comment by andreslucena** [comment]
En principio estaba activada (mostrando un máximo de 30 mensajes), pero no había puesto los botones para ir a las otras páginas. Ya lo puse, debería funcionar todo bien. (Igual 30 es bastante, por supuesto se puede bajar si queremos). Revisalo.

**Comment by iokese** [comment]
ok
