### ISSUE TITLE
Vuelve a fallar refresco numero de mensajes

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#48]
http://beta.nolotiro.org/es/message/list

Yo tengo solo 5 mensajes pero me dice que tengo 33. He borrado todos los otros, pero no actualiza.

**Comment by andreslucena** [comment]
¿En que página lo ves? En principio debería ser un bug solo de una vista en particular ya que no estoy cacheando tan agresivamente eso.

**Comment by iokese** [comment]
Lo veo en mi mensajería privada. Ahora pensando quizás el número de mensajes podría ser la suma de los que están en la papelera y el el inbox, por si te da alguna pista.

**Comment by andreslucena** [comment]
Era eso exactamente Dani, muy buen troubleshooting :) 

Ya debería funcionar teniendo en cuenta el inbox solamente, revisalo.

**Comment by iokese** [comment]
Ok, perfecto.
