### ISSUE TITLE
Admin: poder cambiar ciudad de anuncio

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#5]
En caso de que un usuario lo haya puesto incorrectamente al publicarlo, se necesita la posibilidad de  cambiar de ciudad un anuncio desde el admin.

**Comment by iokese** [comment]
Ahora mismo se puede "por accidente", es decir, entras como admin y ese usuario admin está en una ciudad que tu mismo decides. Después vas al anuncio y al modificaar cualquier cosa te lo pasa a esa ciudad del admin (que debe ser la ciudad donde se quiere poner el anuncio). Esto es en realidad un bug, debería poder hacerse por el panel.

**Comment by deivid-rodriguez** [comment]
Le he echado un ojo a esta issue y a #110. Creo que de momento bastaría con editar la ciudad poniendo el WOEID. Lo suyo sería hacer un buscador como en la app, o algo con autocomplete, pero yo de momento lo dejaría en edición por WOEID, ya que:

- Creo que el sistema de localización de nolotiro tendríamos que repensarlo y, quizá, reimplementarlo totalmente.
- ActiveAdmin me resulta muy rígido con todas esas DSL's. Meterle AJAX, autocompletes y cosas así... pfffff. Creo que deberíamos implementar la consola de admin from scratch o al menos usar algo más flexible: https://github.com/thoughtbot/administrate

-

**Comment by andreslucena** [comment]
+1 a que sea WOEID numerico y punto, sin autocomplete ni nada. 

+1 a que tenemos que repensar/reimplementar esto, lo dejamos así para no liarnos demasiado con la migración de v2 (PHP) a v3 (rails), pero habría que darle una vuelta a ver si hay algo más moderno/optimo para este problema de "organizar el mundo entero".

**Comment by deivid-rodriguez** [comment]
Vale, pues en cuanto revisemos las PR's abiertas, lo implemento. Y para repensar el sistema de localización abrimos otra issue, no?

**Comment by andreslucena** [comment]
:+1:
