### ISSUE TITLE
Adsense: en lista de mensajes

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#50]

**Comment by franciscout** [comment]
Ya esta. Añadidos anuncios de google en /message/list y en la trash.
Puse uno rectangular de 450*280 en desktop y horizontal de 300*60 en responsivo, ¿te parece bien?

**Comment by iokese** [comment]
el anuncio está debajo, debería estar en el lateral igual que en producción.

**Comment by franciscout** [comment]
Ya estaria igual que como esta en produccion; revisar y cerrar?

**Comment by iokese** [comment]
Cuando al pantalla se reduce, el anuncio pasa a estar debajo de los mensajes, debería estar encima o entre medias.

**Comment by andreslucena** [comment]
@iokese de momento yo propongo dejarlo como se ve ahora, con el anuncio por debajo, más que nada porque no es tan facil ponerlo entre medias de los mensajes (usamos una tabla) y tambien puede generar conflicto con los usuarios (clicks dados sin querer) e ir en contra de las guidelines de google. Por otro lado ponerlos arriba cambia con como lo estamos haciendo en otras páginas, asi que lo dejaría abajo.

Tambien refactoricé la parte de como se muestran los mensjaes, ahora aparecerá como una barrita (que no es ideal tampoco, pero es lo que menos tiempo lleva). 

Revisa y comenta a ver que te parece.

**Comment by iokese** [comment]
¿Y ponerlo a la derecha?.

De momento ahora no se ven.

**Comment by franciscout** [comment]
En este lo unico que faltaria es cambiarle a horizontal entre las resoluciones 700/800, fijate si encuentras algun otro fallo

**Comment by franciscout** [comment]
Vale, ya creo que esta bien en todas las resoluciones, que te parece @iokese ??

**Comment by iokese** [comment]
Ahora mismo no veo ningún anuncio en la lista de mensajes.

**Comment by franciscout** [comment]
Que tal ves este ahora, @iokese ?

**Comment by iokese** [comment]
Ok, cierro.
