### ISSUE TITLE
Paginación en portada

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#52]
En producción, abajo del todo, pone "ver más anuncios" en vez de el sistema de paginación. Luego ya sale la paginación. Habría que replica eso aunque propongo aumentar un poco la fuente de "ver más anuncios" para animar a que hagan click. (ahora mismo n 5,7% hace click ahí, me gustaría ver si con eso mejora).

Aparte de eso, la paginación en portada está rota, "atrás" queda fuera del marco.

**Comment by andreslucena** [comment]
Vale, en caso de que querramos aumentar los clicks a esta parte creo q lo mejor sería dejarla con la paginación como está puesta ahora mismo (con los botones de 1 2 3 4 5...) que llama más la atención y la gente lo reconoce facilmente. 

Por otro lado deberíamos ver también que Call2Action tenemos en nuestra página principal. Creo que lo deberíamos potenciar más es el Onboarding de los nuevos usuarios y la publicacion de anuncios nuevos en vez de que vean los anuncios antiguos (que aparte muchos ya habrán sido entregados o reservados).

**Comment by iokese** [comment]
+1

**Comment by andreslucena** [comment]
Vale, para que quede bien le quite las palabras "atras/siguiente" que rompian un poco el diseño. 

Falta que revise bien el tema del diseño responsivo @franciscout

**Comment by franciscout** [comment]
No toque nada, pero creo que ya esta bien en responsivo, yo lo cerraria :+1:

**Comment by iokese** [comment]
En producción está mucho más bonito, con los cuadros separados, aquí una imagen de cómo está en produccioń, debería quedar así:

![paginacion_nolotiro](https://cloud.githubusercontent.com/assets/1123486/7569825/19f2f026-f7d1-11e4-9a03-470e135f7bdc.png)

**Comment by franciscout** [comment]
Ya lo puse asi; revisar y cerrar?

**Comment by iokese** [comment]
Debería poner "<< Anterior" y ""Siguiente >>" en vez de las flechitas.

**Comment by franciscout** [comment]
Okay, ponemos 'Anterior/siguiente' en todas las resoluciones o adaptamos el diseño en responsivo? (estilo, resoluciones menores de 779px ponemos solo las flechas y las mayores, añadimos el anterior/siguiente?

**Comment by iokese** [comment]
ok, adelante.

**Comment by franciscout** [comment]
Ya hice los cambios, revisalo cuando puedas :)

**Comment by iokese** [comment]
Aún es distinto, "anterior" y "siguiente" están dentro de un recuadro, hay que dejarlo como el original, al 100%.

**Comment by andreslucena** [comment]
Mejor que se quede con el recuadro sobre todo para el tema de los móviles, que quede claro el limite de la caja que se puede hacer click y que es un boton.
