### ISSUE TITLE
Botón Facebook en pié

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#53]
Se superpone con "acerca de", hay que separarlos.

Si hace falta, yo quitaría el de google plus que estadísticamente veo que casi no se usa, aparte de que relentiza la carga de la web.

**Comment by franciscout** [comment]
Saque el botón de G+ en los anuncios particulares y el footer; eso hizo que la separación entre "acerca de" y facebook fuera correcta, revisar por las dudas.
