### ISSUE TITLE
Buscar en "busco"

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#54]
Cuando estás en "regalo" y buscas algo todo ok, pero si después de esa búsqueda le das a "busco" te busca lo mismo en "busco". Esto no se si debería ser así, debería aparecer el campo de búsqueda vacío  todo el listado y que le usuario comience a buscar.

Cuando buscas en "busco" te lleva a "regalo" :/

**Comment by andreslucena** [comment]
Ya está solucionado, falta revisarlo.

**Comment by iokese** [comment]
Revisado, todo ok.
