### ISSUE TITLE
Política privacidad y condiciones uso

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#55]
Meter lo recomendado por mayú

**Comment by andreslucena** [comment]
Ya está actualizado lo que comentaba txema: 

* Revisión de http://beta.nolotiro.org/es/page/privacy
* Agregar http://beta.nolotiro.org/es/page/legal
* Agregar mensaje de cookies como barra abajo (quitando de las notificaciones normales de nolotiro)

Falta revisarlo.

**Comment by iokese** [comment]
Falta parte de lo que nos indicaban en otro correo: "Ah, por cierto, también sería conveniente que añadierais esa típica frase de que os reserváis el derecho a cambiar las condiciones y términos del servicio sin previo aviso y que por tanto las usuarias deberán revisar las mismas regularmente  o reservaros ese derecho pero avisad por mail a las usuarias registrsadas cuando hagáis algún cambio."

**Comment by andreslucena** [comment]
Agregado al final de http://beta.nolotiro.org/es/page/privacy

**Comment by iokese** [comment]
ok.
