### ISSUE TITLE
Texto enviar mensaje en regalo

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#56]
En beta: Envía un mensaje al anunciante
En producción: Envía un mensaje privado al anunciante

Debe poner lo mismo que en producción.

**Comment by andreslucena** [comment]
Vale, ya ponemos lo mismo que en producción en donde ponemos lo de enviar un mensaje. Revisalo.

**Comment by iokese** [comment]
ok

**Comment by iokese** [comment]
Pero se ha descentrado todo el texto del footer....

**Comment by andreslucena** [comment]
Por footer te referias a la parte de abajo de cada anuncio de la portada, no? 

Ya está arreglado, revisarlo.

**Comment by iokese** [comment]
Ok.
