### ISSUE TITLE
Textos en Mensaje

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#57]
http://nolotiro.org/es/message/create/id_user_to/92387/subject/ropita-nina
http://beta.nolotiro.org/es/message/create/id_user_to/92387/subject/ropita-nina
* En producción: 
 *  Por favor, escribe tu mensaje
 * Tema

* En Beta
 * Enviar mensaje
 * Subject

Debe quedar igual que en producción

**Comment by andreslucena** [comment]
Solucionado. Falta revisarlo (creo que el diseño cambia un poco pero tampoco se nota demasiado).

**Comment by iokese** [comment]
Ok.
