### ISSUE TITLE
No se pueden hacer comentarios

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#6]
Al intentar hacer un comentario en cualquier anuncio da error.

**Comment by andreslucena** [comment]
Ya está funcionando, era lo del envio de correo. De momento hice un fix momentario (byobu con mailcatcher) pero he creado el ticket #12 para que no vuelva a repetirse.

**Comment by iokese** [comment]
Ya funciona. ¿cerramos este ticket?

**Comment by jipipayo** [comment]
os veo a tope! cuando inaugurais la nueva version???? animo compays!!!

**Comment by andreslucena** [comment]
Pues el plan era para el 31 de marzo pero hay algún detalle que todavía falta por controlar (los tickets abiertos y un problema que hay con cancelar la cache después del deploy), asi que lo retrasamos para el 15 de abril para llegar más tranquilos :)
