### ISSUE TITLE
Comportamiento del 1er boton verde en las diferentes resoluciones/paginas

### ISSUE THREAD

**Issue by franciscout** [alabs/nolotiro.org#60]
El boton verde (.ad_create_tab/.ad_create_tab_home) esta mal optimizado para el responsivo y cambia de comportamiento en las diferentes paginas (frontpage y la pagina de cada ciudad); por lo que tengo que revisarlo y repararlo.

**Comment by iokese** [comment]
Todavía no está centrado.

**Comment by franciscout** [comment]
Hay que terminar de revisar en las diferentes resoluciones, tiene dos variantes, una en la pagina principal y otra en la lista de ciudad.
Me parece que no queda tan lindo entre 500px y 779px, reduzco tamaño y lo pongo mas a la derecha (mas parecido a como esta en produccion?

**Comment by iokese** [comment]
Lo veo mejor.

**Comment by franciscout** [comment]
Ya esta :)

**Comment by iokese** [comment]
Ok, cierro.
