### ISSUE TITLE
Adsense: listado de anuncios en Chrome

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#61]
Se mueve el adsense a la izquierda y tapa al resto. 

http://beta.nolotiro.org/es/woeid/766273/give

**Comment by franciscout** [comment]
En general esta bien, no veo ningún bug ni en Chrome ni en IE (por lo menos, en el 11)

Yo cerraría el issue; que te parece a ti, @iokese ??

**Comment by iokese** [comment]
No tengo IE ni chrome, solo veo mal con Chromium los de la portada, pero no se si es por otra cosa más que por el navegador.

**Comment by iokese** [comment]
En portada no se ven con ningún navegador.

**Comment by franciscout** [comment]
Si, tienes razon, acabo de hacer un push para un fix que soluciona eso.

**Comment by iokese** [comment]
Solo se ve 1 y de un tamaño desproporcionado, debe haber 3 como en producción,

**Comment by franciscout** [comment]
En la portada ya hay 3 horizontales, creo que este issue ya esta resuelto (no encuentro ningun otro bug en chrome, habria que ir revisando en diferentes browsers a ver que falla)

**Comment by andreslucena** [comment]
Este tambien se podría cerrar por mi parte.
