### ISSUE TITLE
Adsense: listado de anuncios de un usuario

### ISSUE THREAD

**Issue by andreslucena** [alabs/nolotiro.org#62]
El adsense aparece abajo de todo y debería aparecer en el espacio que hay a la derecha. Se puede hacer un poco menos ancho la parte con todos los anuncios.

**Comment by franciscout** [comment]
Ya esta puesto el vertical, ahora estoy revisando para que quede bien cuando el usuario no tiene ningún anuncio (se come parte del footer).

**Comment by franciscout** [comment]
Ya estaria bien puesto, no se come nada del footer, revisar y cerrar?

**Comment by iokese** [comment]
Cuando la página se "estrecha", el banner pasa a ser cuadrado y eso es OK, pero debería estar arriba del todo o entre los primeros anuncios de regalo en vez de abajo del todo.

**Comment by franciscout** [comment]
¿que tal lo ves ahora?

**Comment by iokese** [comment]
Ahora no veo el add :/

**Comment by andreslucena** [comment]
@iokese te lo pongo solo en este ticket pero sería para todos. He refactorizado bastante lo que es el tema del adsense a ver si falla menos para el tema del responsivo. 

Relacionada con #50 #25 #61 #62

**Comment by iokese** [comment]
De momento no veo casi publicidad en la web.

**Comment by andreslucena** [comment]
Ahora sí, con los últimos cambios debería verse todo. Creo que ya se puede cerrar esto - aunque tiene poco anuncios, pero se ven bien, ya iremos tuneando la cantidad/disposicion/tamaño de los anuncios segun vayamos necesitandolo.

**Comment by franciscout** [comment]
Si, @andreslucena  abri el #76 como paraguas para todos estos temas, segun vayamos encontrando lo ponemos ahi y en la siguiente actualizacion lo ponemos todo junto.
Parece que este bug ya esta resuelto, que te parece @iokese ??

**Comment by iokese** [comment]
Ahora no me sale ningún anuncio en el listado de anuncios de un usuario :/

**Comment by andreslucena** [comment]
Ya está cambiado, se me habí pasado.

**Comment by iokese** [comment]
Ok.
