### ISSUE TITLE
Adsense: En la página de regalo el add no es el que corresponde

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#63]
El que hay es mucho más pequeño.

**Comment by franciscout** [comment]
Creo que ya esta todo, @iokese puedes revisar y cerrar si lo ves bien?

**Comment by iokese** [comment]
Ahora no veo ningún add :/

**Comment by franciscout** [comment]
Estamos hablando de las paginas particulares de cada anuncio, no? estilo es/ad/xxxx/anuncio-etcetera?

**Comment by iokese** [comment]
Correcto.

**Comment by franciscout** [comment]
Revisa a ver si tu browser esta todo bien configurado, y también acuérdate de apretar F5/ctrl+r para que se recargue la petición de anuncio a google cuando redimensionas la ventana

**Comment by iokese** [comment]
Ok, lo cierro.
