### ISSUE TITLE
No cambia la portada

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#64]
Cuando estás sin loguear en la portada de nolotiro y le das a la siguiente página vuelve a mostrarte la lista de ciudades y de usuarios. Debería pasar como en producción, que la lista de ciudades y usuarios solo sale en la portada y no en las siguientes páginas.

**Comment by andreslucena** [comment]
Ya está puesto en la beta. Con esto cambiamos la paginación, relacionada con #52 

Falta revisar.

**Comment by iokese** [comment]
Ok.
