### ISSUE TITLE
Texto: Lista de anuncios

### ISSUE THREAD

**Issue by franciscout** [alabs/nolotiro.org#65]
En la lista de anuncios particular (/ad/listuser/id/xxxxx) cuando un usuario no tiene ningun anuncio no tiene ningun aviso, mientras que en produccion el usuario recibe el aviso de " Este usuario no tiene anuncios todavía".

**Comment by andreslucena** [comment]
Hecho, revisarlo.

**Comment by franciscout** [comment]
Perfecto :+1:

**Comment by iokese** [comment]
Ok.
