### ISSUE TITLE
Adsense: Listado de mensajes

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#66]
Aparece el banner a la derecha en ve de a la izquierda.

**Comment by franciscout** [comment]
Esta relacionado con los cambios hechos para #62 y #50, (hay bugs similares en los dos, lista de anuncios y de mensajes). Se lo que causa el problema pero en los test que hice en el server local no me pasaba. 

En el siguiente commit voy a revertir estos cambios e intentare solucionar los dos bugs abiertos.

**Comment by franciscout** [comment]
Duplicado de #50
