### ISSUE TITLE
Boton de FB roto

### ISSUE THREAD

**Issue by franciscout** [alabs/nolotiro.org#67]
El boton de 'like' en facebook con un texto que dice 'Unable to connect', en el footer y en el anuncio. Hace poco actualice Firefox a la version 38, no estoy seguro si esta relacionado.

**Comment by franciscout** [comment]
@iokese te ocurre esto en el boton de fb? 
A @andreslucena no le ocurre, por lo que no se si es un bug propio o es algo mas comun

Yo lo veo asi: 

![nlt bug fb](https://cloud.githubusercontent.com/assets/6383798/7677622/e534da34-fd4d-11e4-9be7-61a74d0221d3.jpg)

**Comment by iokese** [comment]
Lo vi así durante varios días, ahora se ve bien.

**Comment by iokese** [comment]
Se ve bien, cierro.
