### ISSUE TITLE
Separar   "+ Envía un mensaje al anunciante    + Escribe un nuevo comentario"

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#69]
Están demasiado juntos, hay que separarlo un poco más como en producción.

**Comment by andreslucena** [comment]
Ya está soucionado, aproveché para poner las lecturas un poco más pequeñas y a la izquierda, se ve un poco mejor. Revisarlo.

**Comment by iokese** [comment]
Ok.
