### ISSUE TITLE
No tengo botón "publicar anuncio"

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#7]
No veo el botón de publicar anuncio al estar logueado.

**Comment by andreslucena** [comment]
Ya estaría solucionado, era un problema con las imagenes que algunas me las tomaba como HTTPS y eso hacía que no aparecieran. Aparte al arreglar esto no se actualizó ya que la cache se quedó con la página antigua. Ya estarían solucionadas las dos cosas.

**Comment by iokese** [comment]
En "todos los anuncios" sigue sin salir el botón de publicar anuncio: http://beta.nolotiro.org/es/ad/listall/ad_type/give

Si se ve en la página de una ciudad, pero no en "todos los anuncios".

**Comment by andreslucena** [comment]
Ya he puesto el botón en "todos los anuncios".
