### ISSUE TITLE
Mensajería: Al responder un mensaje pone una hora distinta

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#70]
Dice que respondí hace 7 horas, pero acabo de responder.

**Comment by andreslucena** [comment]
Ya debería estar solucionado en la beta, le cambie la zona horaria. Revisar.

**Comment by iokese** [comment]
Sigue funcionando, incluso peor, ahora me dice que el comentarío será en el futuro.
![captura de pantalla de 2015-05-19 13 34 42](https://cloud.githubusercontent.com/assets/1123486/7710811/e4f619d2-fe2b-11e4-8ccc-325ad328cf50.png)

**Comment by andreslucena** [comment]
Vale, ya lo revise haciendo cambios en mi ordenador, sin tener en cuenta la zona horaria que se estaba liando, llevandolo todo a UTC. Ahora si debería ir bien.

**Comment by iokese** [comment]
Ok.
