### ISSUE TITLE
Refresco: Al publicar  anuncio dice que lo hice hace 7 horas

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#71]
Cuando lo creo y acepto, me lleva a la página del regalo y dice que lo creé hace 1 minuto, pero al volver  la portada dice que lo creé hace 7 horas.

**Comment by andreslucena** [comment]
Relacionada con #70 

Ya debería estar solucionado en la beta, le cambie la zona horaria. Revisar.

**Comment by iokese** [comment]
Acabo de publicar uno y dice que lo publiqué hace 7 horas.

**Comment by andreslucena** [comment]
Lo mismo que con #70 : 

"Vale, ya lo revise haciendo cambios en mi ordenador, sin tener en cuenta la zona horaria que se estaba liando, llevandolo todo a UTC. Ahora si debería ir bien. "

**Comment by iokese** [comment]
Ok.
