### ISSUE TITLE
Caja mensaje se puede agrandar demasiado

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#72]
Cuando escribes un mensaje privado puedes redimensionar la caja hasta que se mete debajo del add.
![captura de pantalla de 2015-05-18 10 28 57](https://cloud.githubusercontent.com/assets/1123486/7684060/d1590968-fd48-11e4-8197-b5fcb2d6032c.png)

**Comment by andreslucena** [comment]
Ya estaría solucionado, revisar en la beta.

**Comment by iokese** [comment]
Ya no se puede redimensionar, ok. pero desapareción la publicidad y el cuadro ha quedado descentrado, adjunto imagen,
![captura de pantalla de 2015-05-19 13 36 43](https://cloud.githubusercontent.com/assets/1123486/7710849/2cb0aaf8-fe2c-11e4-99e5-fee735da49ad.png)

**Comment by andreslucena** [comment]
OK, ya lo he revisado, ahora debería quedar bien como en las otras páginas.

**Comment by iokese** [comment]
Yo lp veo exactamente igual (mal),
