### ISSUE TITLE
Limitar cantidad de texto en mensajes privados

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#74]
Ahora mismo no hay límite, yo probaría con uno de 2.500 caracteres.

Ejemplo: http://beta.nolotiro.org/es/messages/224342

**Comment by andreslucena** [comment]
Ya está limitado a 2500. Revisarlo.

**Comment by iokese** [comment]
Acabo de volver a meter 11.000 caracteres y me ha dejado: http://beta.nolotiro.org/es/messages/224342

**Comment by iokese** [comment]
Yo solo veo 1, puede ser que google no nos esté enviando los otros 2?

**Comment by andreslucena** [comment]
Ya debería estar, lo puse donde no era. Revisalo.

**Comment by iokese** [comment]
Perfecto, pero son muchísimos, yo lo dejaría en 1.500 y ya directamente lo puedes cerrar.

**Comment by andreslucena** [comment]
Hecho y subido, revisarlo.

**Comment by iokese** [comment]
El contador dice que el limite siguen siendo 2.500.

**Comment by andreslucena** [comment]
Corregido

**Comment by iokese** [comment]
ok, cierro.
