### ISSUE TITLE
1º mensaje de un usuario

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#75]
Cuando un usuario nuevo se registra y envía su primer mensaje a otro usuario no puede ver ese mensaje en ningún sitio. Solo lo puede ver cuando el otro usuario le contesta.

**Comment by andreslucena** [comment]
Vale, he vuelto a poner la pestaña de mensajes Enviados. Tambien he quitado lo de "Enviado/Recibido" ya que no tenía sentido, y he dejado solamente el nombre de la persona con la que uno se comunica. Revisa como queda, yo creo que es bastante más claro que antes.

**Comment by iokese** [comment]
Vale, por mi lo podemos cerrar hasta que hagamos bien la mensajería.
