### ISSUE TITLE
Adsense: mejorar anuncios

### ISSUE THREAD

**Issue by franciscout** [alabs/nolotiro.org#76]
Ya después de actualizar producción, habría que ir revisando el uso periódico de la pagina, fijarse cuales son los anuncios mas rentables e ir modificando a partir de ahí.

**Comment by andreslucena** [comment]
Relacionado con #92 - lo que dice @franciscout sumandole esto: 

"Revisar en la beta, pagina por pagina, el tipo de anuncio que es, si es correcto, si hacen falta más, si hay que cambiarlo, etc, para los 3 tipos de dispositivos (desktop, tablet y mobile). "

@iokese nos tenemos que sentar a revisar esto.

**Comment by deivid-rodriguez** [comment]
Voy a cerrar esto y subdividir la tarea en dos issues.

**Comment by deivid-rodriguez** [comment]
Cerrada en favor de #333 y #346.
