### ISSUE TITLE
Adsense: Falta ad en cambio ciudad

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#78]
Y también falta al continuar el proceso de cmabio de ciudad, en la siguiente página tampoco está el ad.

**Comment by franciscout** [comment]
Vale, ya tenemos los anuncios, falta reducirlos para que quede igual que en produccion (antes que lo digas vos ;) )

**Comment by franciscout** [comment]
Vale, ahi estan, los ves bien?

**Comment by iokese** [comment]
Ok.
