### ISSUE TITLE
Error al poner comentario demasiado largo

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#79]
Al poner un comentario muy largo (probad aquí: http://beta.nolotiro.org/es/ad/190066/regalo-confirmar-el-funcionamiento-del-refresco) me da error, y no me especifica nada.

Hay que poner el mismo límite que hay en producción.

**Comment by andreslucena** [comment]
OK, corregido para que muestre el error, el limite como ayuda y que no deje poner mas de los 1000 caracteres. Este es el mismo limite que tenemos en produccion. 

Revisarlo.

**Comment by iokese** [comment]
ok, cierro.
