### ISSUE TITLE
No funciona la mensajería

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#8]
No funciona nada.

**Comment by andreslucena** [comment]
Exactamente que es lo que no funciona? Ver mensajes? Enviar mensaje nuevo? Responder?

**Comment by iokese** [comment]
No puedo responder a mensajes. Cuando lo intento logro rellenar el cuerpo del mensaje pero al darle a enviar me da timeout. Lo mismo me pasa al enviar un mensaje nuevo.

**Comment by andreslucena** [comment]
OK, creo que esta relacionada con la #6, que esta intentando conectarse al server SMTP. Le voy a poner mailcatcher (guarda los correos en vez de enviarlos). Te aviso cuando lo tenga.

**Comment by andreslucena** [comment]
Ya está funcionando, era lo del envio de correo. De momento hice un fix momentario (byobu con mailcatcher) pero he creado el ticket #12 para que no vuelva a repetirse.
