### ISSUE TITLE
Adsense: Revisar ad lateral

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#80]
Parece que es de 120X600 en vez de 160X600 como en producción.

**Comment by franciscout** [comment]
Vale, ya tiene 160px disponibles google (hay veces que te pone menos tamaño, pero en general sale 160px)

**Comment by franciscout** [comment]
Lo ves bien, @iokese?

**Comment by iokese** [comment]
Sí, lo cierro.
