### ISSUE TITLE
El botón "Publicar anuncio" tiene demasiada info

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#81]
En producción hay menos info en ese botón, hay que dejarlo como en producción,

Queda feo que repita el nombre de la ciudad o que de tantos detalles. El usuario ya está asociado a una ciudad y no necesita ver tanta info.

**Comment by franciscout** [comment]
Hicimos una refactorizacion de todo el tema de los nombres de las ciudades, voy a estar buscando bugs. @iokese  si ves un texto que sea estilo " {:full=>"Madrid, Madrid, España", :short=>"Madrid"} " es un bug de este tipo y estaria bueno si los concentramos todos en este issue :)
