### ISSUE TITLE
Botones de páginas descolocados

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#84]
Sale en dos líneas como se ve en este screenshot

![captura de pantalla de 2015-09-05 14 08 37](https://cloud.githubusercontent.com/assets/1123486/9700822/ac45b8fc-53d7-11e5-934b-cbab968d2f2c.png)

**Comment by franciscout** [comment]
Solucionado, @iokese  cuando puedas lo revisas? :)

**Comment by iokese** [comment]
Lo sigo viendo igual (siempre con el teléfono móvil)

**Comment by franciscout** [comment]
Si, en el movil se hace rompe la linea cuando pasan de tres numeros cada indicador de pagina, ahora lo cambio

**Comment by iokese** [comment]
SI está solucionado puedes cerrar este ticket,

**Comment by franciscout** [comment]
cuando sobrepasa los tres numeros la paginación el next se mueve a la siguiente linea, pero porque llega al máximo por resolución del movil. 

supongo que no hay much@s usuaros que lleguen tan lejos por lo que no creo necesario haceras cambios

**Comment by iokese** [comment]
ok, cierro.
