### ISSUE TITLE
Agregar una función que permita informar de un contenido inapropiado

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#86]
Ejecutar tarea Uservoice: http://nolotiro.uservoice.com/forums/30282-espa%C3%B1ol/suggestions/1247889-agregar-una-funci%C3%B3n-que-permita-informar-de-un-con

**Comment by andreslucena** [comment]
OK. de momento lo que tengo hecho (subido a la beta) es una integración con Akismet en el admin, que marca los comentarios como spam o como no spam a mano. De momento solo los marcamos, NO los ocultamos ni borramos ni nada. 

Lo siguiente que haré es que los usuarios tambien puedan denunciar contra Akismet, pero que este reporte se realice al juntarse N cantidad de reportes de spam (por ejemplo 5 reportes de spam a un mismo anuncio, que ahi avise a akismet, y que en el admin podamos ver los anuncios marcados como spam).

**Comment by jipipayo** [comment]
+1

**Comment by iokese** [comment]
- [ ] Introducir en el FAQ la explicación de la banderita.
- [ ] Notificación a todos los usuarios: Explicación de la banderita y de su buen uso.
- [ ] Poner una banderita en gris.
- [ ] Al pasar el ratón un texto explica que vas a reportar el anuncio y bloquear al usuario.
- [ ] Al hacer click sale un mensaje que confirma que has reportado ese anuncio y boqueado al usuario.
- [ ] La banderita pasa a rojo y al pasar el ratón por encima avisa que ya has reportado el anuncio.

**Comment by deivid-rodriguez** [comment]
:+1: Lo único que creo que el bloqueo lo podemos dejar de lado de momento. Sólo reportar. 

Por otro lado, la lógica interna podría ser:

* Los anuncios no se muestran si tienen el flag de spam a `true` o si tienen el flag de spam a `nil` y 3 o más reportes.
* Los anuncios se muestran si tienen el flag de spam a `false` o si tienen el flag de spam a `nil` y menos de 3 reportes.

Esto permite la lógica de bloqueos por reportes, pero también override fácil desde el admin.

**Comment by andreslucena** [comment]
:+1: a todo lo que comentas, lo unico que cambiaria es que igual esto de:

>  Al pasar el ratón un texto explica que vas a reportar el anuncio y bloquear al usuario.

No es compatible con dispositivos moviles que no tienen un rato como tal y no cuentan con hover, asi que igual puede ser con click directamente, o la UI que veas mejor @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
Es verdad, en hover no mola. Cuando llegue a ello pienso algo.

Luego está el tema del numerito. @iokese tiene miedo de ponerlo muy bajo y que la gente use mal la feature. Yo tengo miedo de ponerlo muy alto y que la feature no sea efectiva.

**Comment by andreslucena** [comment]
Ya, en principio puede ser un poco arbitrario, mi preocupación va sobre todo por la diferencia que tenemos entre las ciudades con más visitas y las otras que pueden no tenerlas tantas. ¿Igual esto se resuelve con un ratio muy simple entre denuncias y numero de vistas que haya tenido este anuncio? Creo que no es una solución muy óptima porque el número de visitas es bastante hackeable (con refresh, sin comprobar IPs ni nada).

**Comment by deivid-rodriguez** [comment]
Yo lo lanzaría con un límite bajo y vería.

Si ponemos, subiendo un poco mi primera propuesta, 5 de límite, harían falta 6 usuarios (o clones) tramposos simultáneos que se pusieran de acuerdo para banear el mismo anuncio... Yo creo que cazamos a los tramposos antes de que sus reportes tenga efecto.

**Comment by erm3nda** [comment]
Yo lo que haría es dar esa función sólo a usuarios que lleven años en la página, que hayan tenido actividad real, y que estos os hagan de free testers. Eso os dirá sin ningún tipo de setup previo, que uso le pretende dar la gente, y si véis que le dan demasiado alegremente, haced sólo un conteo por USUARIO, nada de visitas, ips ni leches. No te logueas, no tienes derecho a marcar nada, y un botón al lado que ponga "registrate" y bloquea a este parguelas.

Las personas de verdad no hacemos el troll innecesariamente, aunque no porque no podamos, es porque no renta...

> tramposos simultáneos que se pusieran de acuerdo para banear el mismo anuncio

Si tan ahí llega la cosa... entonces necesitas un algoritmo, que detecte trolls en masa. Si 20 usuarios me marcan esto A LA VEZ, deduciré que son 1 o 2 trolls y sólo contaré 1 o 2 trolls... no más. IP, geoip y cualquier otra cosa quien quiera se la salta. Usuarios noveles no pueden usarlo, así evitas que se hagan cuentas nuevas para trolear.

Disculpadme si lo puse todo un poco al tuntún, pero eso lo que pienso al respecto.

Saludos.

**Comment by deivid-rodriguez** [comment]
Sí, el enfoque que tengo empezado en local va por ahí.
