### ISSUE TITLE
Volver a poner los anuncios, sin necesidad de borrarlos y volver a crear otro

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#87]
http://nolotiro.uservoice.com/forums/30282-espa%C3%B1ol/suggestions/1068173-poder-volver-a-poner-tus-anuncios-adelante-de-la-p

**Comment by deivid-rodriguez** [comment]
La próxima vez que tenga tiempo para nolotiro, me gustaría implementar esta issue. Como usuario la veo muy útil para volver a "lanzar" las cosas que no pudiste regalar a la primera. Habría que definir algunas cosas, tanto a nivel de diseño como de funcionamiento:

- Cómo llamamos a la funcionalidad para que se entienda? "Republicar"?
- Qué tiempo mínimo definimos para poder republicar?
- Dónde situamos el botón, junto a "editar"? Permitimos un "editar y republicar" a la vez?
- Dónde y cómo explicamos la feature a nivel de interfaz?

Saludos.

**Comment by andreslucena** [comment]
+1 a todo

El termino republicar me parece que queda claro. A mi se me ocurría "Promocionar", pero creo que la gente se puede confundir y pensar que pedimos dinero por ello. Otro más: "volver a darle visibilidad" pero mola más si es una sola palabra. 

Pondría un tiempo míniimo de 24 o 12 horas, muchas veces se va a querer republicar porque quieren sacarse de encima al objeto cuanto antes. 

A nivel de UI, estaba pesando alguna otra aplicación que haga esto o similar. Se me ocurre que en los foros hay veces que los usuarios se autoresponden el mensaje diciendo "bump" para esto ( http://www.urbandictionary.com/define.php?term=bump ) pero es justamente un hack y no forma parte de la UI en ningun lado. Esto es lo mas parecido que me suena a lo que queremos hacer :P

**Comment by deivid-rodriguez** [comment]
> El termino republicar me parece que queda claro. A mi se me ocurría "Promocionar", pero creo que la gente se puede confundir y pensar que pedimos dinero por ello. Otro más: "volver a darle visibilidad" pero mola más si es una sola palabra. 

"Visivilizar" sería una sóla palabra pero me gusta más "Republicar". En el hilo que enlaza @iokese donde se discute el tema también se menciona "relanzar".

> Pondría un tiempo míniimo de 24 o 12 horas, muchas veces se va a querer republicar porque quieren sacarse de encima al objeto cuanto antes. 

Mi sugerencia (se me olvidó ponerlo en el anterior mensaje) sería ~ 1 semana. La discusión en el hilo enlazado es interesante. Abusar de "republicar" hará que "primeras publicaciones" queden rápido sepultadas y además los usuarios que consulten frecuentemente la página lo considerarán "spam" ya que si no les interesó en su momento, seguramente no les va a volver a interesar y no querrán volver a ver el anuncio. Enlazando con esto, habría que definir cómo se comporta el feed RSS con respecto a republicaciones.

**Comment by iokese** [comment]
+1 a una semana, ¿quizás poner un límite de "relanzar" a 10 anuncios para evitar que saturen?. Respecto a los RSS, igual no pasa nada, se cumple la función de volver a ponerlo por si alguien no lo ha visto.

**Comment by iokese** [comment]
Pensándolo de nuevo podrían ser sólo 5 días en vez de 7. 
+1 a "Republicar", ¿directamente en vez de editar? Debería salir sólo en los regalos que están disponibles (no en los pendientes o entregados) cuando han pasado 5 días.

**Comment by deivid-rodriguez** [comment]
> Pensándolo de nuevo podrían ser sólo 5 días en vez de 7. 

Me parece bien 5 días.

> ¿quizás poner un límite de "relanzar" a 10 anuncios para evitar que saturen?

Entiendo que sería un límite por plazo de tiempo, como un relanzamiento al día o algo así? En cualquier caso, yo lo implementaría de momento sin ningún límite de este tipo y vería primero cómo se comporta.

> Respecto a los RSS, igual no pasa nada, se cumple la función de volver a ponerlo por si alguien no lo ha visto.

Ok.

> Debería salir sólo en los regalos que están disponibles (no en los pendientes o entregados) cuando han pasado 5 días.

Correcto.

> ¿directamente en vez de editar?

Yo diría de añadir otro botón "republicar" al lado del de "editar", y además que el formulario de editar republique o no de manera inteligente, dependiendo de si estamos o no dentro del plazo. Esto último no lo tengo claro, pero creo que deberíamos incorporar una función "editar y republicar" en un paso. Hoy, por ejemplo, me hubiera gustado editar uno de mis anuncios que es un pack de camisetas al que añado un par de camisetas más y directamente republicarlo con la nueva información.

**Comment by andreslucena** [comment]
+1 a todo lo que comentan (poner otro botón como editar, 5 días, que solo aparezca cuadno se permita la accion). Igual tampoco veo tan interesante la opción de "Editar y republicar", si "Republicar" es solo un botón y se hace rápido.

**Comment by andreslucena** [comment]
Ya está subido a producción, gracias @deivid-rodriguez !!

**Comment by deivid-rodriguez** [comment]
Gracias a ti! :)
