### ISSUE TITLE
Fechas creación usuarios

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#88]
Todos los usuarios tiene fecha de creación "Miembro desde: 20 de julio de 2010".

Con suerte los nuevos tendrán fechas normales, ojalá se pueda recuperar de alguna bbdd anterior la fecha de algunos de ellos.

**Comment by andreslucena** [comment]
Coincide con la puesta en marcha de la v2: https://github.com/alabs/nolotiro/graphs/contributors 

Asi que se cierra ya que son usuarios que se migraron correctamente a la v3. De hecho los primeros son del 22/20 de Julio de 2010: 

http://nolotiro.org/es/profile/4
http://nolotiro.org/es/profile/2
