### ISSUE TITLE
Diseño cambio de ubicación

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#89]
![captura de pantalla de 2015-09-05 22 13 50](https://cloud.githubusercontent.com/assets/1123486/9702348/40b3c61e-541e-11e5-8784-d589c5ddf13c.png)

El cuadrado no cierra bien, y la ciudad no se ve muy clara, debería resaltarse más.

**Comment by franciscout** [comment]
Solucionado, @iokese cuando puedas lo revisas? :)

**Comment by iokese** [comment]
Ok, pero ha desaparecido la publicidad, dejo el ticket abierto hasta que esté de nuevo.

**Comment by franciscout** [comment]
Asi lo veo yo en la beta

![screen shot 2015-09-11 at 07 40 47](https://cloud.githubusercontent.com/assets/6383798/9807785/84afc276-5858-11e5-8398-8180454cdccf.png)

![screen shot 2015-09-11 at 07 41 06](https://cloud.githubusercontent.com/assets/6383798/9807787/86657c6e-5858-11e5-99f2-817442d75e04.png)

**Comment by iokese** [comment]
ok, cierro.
