### ISSUE TITLE
Paginación mensajería usuario

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#90]
Se produce un salto de línea.

![Uploading Captura de pantalla de 2015-09-05 22:45:31.png…]()

**Comment by andreslucena** [comment]
@franciscout esto es backend o frontend? Entiendo que es del CSS y el responsive, no?

**Comment by franciscout** [comment]
Si, se me escapo la etiqueta :-1:

**Comment by iokese** [comment]
Solucionado.
