### ISSUE TITLE
No va publicidad en página ciudad

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#92]
Con el terminal móvil no sale la publicidad en la pagina de ciudad.

**Comment by iokese** [comment]
Yo sigo sin verla en mi Android.

**Comment by franciscout** [comment]
Lo veo asi en la beta, queda por mejorar que usen mejor el espacio.

![20150910224703](https://cloud.githubusercontent.com/assets/6383798/9807855/68aa9168-5859-11e5-8e90-33ce89775da8.jpg)

![20150910224710](https://cloud.githubusercontent.com/assets/6383798/9807856/6ac21b60-5859-11e5-8a8d-bc005dcb1a42.jpg)

**Comment by iokese** [comment]
Ya aparecen, aunque no se puede hacer click para poner comentarios o casi nada.

**Comment by apardo** [comment]
¿Qué le falta a este ticket?

**Comment by andreslucena** [comment]
El problema es que al acceder a algunas paginas de la beta no se visualiza la publicidad de adsense. 

http://beta.nolotiro.org/es/woeid/766273/give
http://beta.nolotiro.org/es/ad/196392/necesito-muebles-urgente

En la consola de javascript se ve el siguiente error: 

  TagError: adsbygoogle.push() error: No slot size for availableWidth=0

![captura de pantalla_2015-09-15_16-35-24](https://cloud.githubusercontent.com/assets/717367/9890785/c9a52a3e-5bc7-11e5-93a2-b05a5800292c.png)

Esto ocurre en Firefox. En Chrome una de las dos paginas que envie se ve la publicidad y en la otra no, apareciendo el error: 

  adsbygoogle.js:5 Uncaught TagError: adsbygoogle.push() error: No slot size for availableWidth=0

Tiene que ser que no le estemos pasando bien algunos parametros para el tamaño/formato que hizo @franciscout en app/views/partials/_google_adsense.html.erb

**Comment by franciscout** [comment]
Respecto al primer link, creo que fue un bug de diseño que estoy haciendo push ahora para arreglarse (los google ads estaban al final de todos los anuncios de nlt), el #106 .

Yo el error de JS (`TagError: adsbygoogle.push() error: No slot size for availableWidth=0`) que menciona @andreslucena lo he estado buscando pero parece estar relacionado a como manejamos la publicidad de Google. En algunas paginas, como por ejemplo el listado de ciudades y el listado general de anuncios, hay en realidad dos sets de google ads: uno para movil y otro para desktop, ya que estan distribuidos de manera diferente (en el movil, al principio y al final de la lista tenemos un google ad o cada 6 anuncios; y desktop hay dos al costado derecho de la pantalla), para que esto ocurra le asigno display:none a uno u a otro (dependiendo del ancho de la pantalla)... ahora lo que pasa es que el container de ese anuncio no tiene width asignada (ya que no se muestra) pero google sigue recibiendo la peticion a traves de JS.

**Comment by andreslucena** [comment]
Me cambié de ordenador y seguia teniendo el mismo bug en Firefox. Lo cambie para dejar de usar el responsive y hardcodear directamente le tamaño qeu queremos el Ad. En pricnipio asi funciona en todas las paginas (ningun error de availableWidth) pero supone revisar de nuevo todas las paginas  (en desktop/table/mobile) para asegurarse que se vean todas bien. Esta todo subido a master.

**Comment by andreslucena** [comment]
En principio esto se soluciona con mi último commit, ahora falta lo siguiente: 

Revisar en la beta, pagina por pagina, el tipo de anuncio que es, si es correcto, si hacen falta más, si hay que cambiarlo, etc, para los 3 tipos de dispositivos (desktop, tablet y mobile). Lo pasamos al ticket #76
