### ISSUE TITLE
Filtrar estas palabras

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#95]
Whatsapp whatsup watsup guasap

**Comment by andreslucena** [comment]
¿Que hacemos con el filtro? ¿Que quite las palabras o no lo deje guardar? Se me ocurre darle un mensjae de error que diga 

     "Cuidado con publicar tu número de teléfono en Internet. No lo recomendamos, si quieres enviarlo hazlo a través de mensajes privados una vez que un usuario interesado te contacte".

**Comment by iokese** [comment]
+1

**Comment by andreslucena** [comment]
Vale, he encontrado que teniamos un filtro para los numeros de telefono, reutilizando ese filtro ya quitamos estas palabras de whatsapp y derivados. Lo que hace el filtro es quitarlas directamente.

**Comment by iokese** [comment]
Parece que ha dejado de funcionar, vuelve a aparecer la palabra whatsupp en varios anuncios 

https://nolotiro.org/es/ad/207415/regalo-sofas
https://nolotiro.org/es/ad/207416/armario-mueble-cama-abatible

**Comment by deivid-rodriguez** [comment]
Lo reviso. De todas formas el tema de los filtros que tenemos ahora mismo (quitar directamente números de teléfono, etc) no me convence nada.

**Comment by deivid-rodriguez** [comment]
@iokese En realidad sí que está funcionando, sólo que "whatsupp" no está entre las 14 variaciones que ahora mismo tenemos para escribir la palabra... Yo diría que con eliminar el número de teléfono vale, ¿qué ganamos eliminando estas palabras específicamente (que son muchísimas combinaciones y siempre se nos va a escapar alguna)?
