### ISSUE TITLE
Error al publicar regalo

### ISSUE THREAD

**Issue by iokese** [alabs/nolotiro.org#97]
En vez de el texto de la ciudad sale esto: "Publicando anuncio - {:full=>"Tucumán, Tucumán, Argentina", :short=>"Tucumán"}".

**Comment by franciscout** [comment]
@iokese , en que url estas cuando encontras ese bug??

**Comment by iokese** [comment]
@franciscout  en esta: http://nolotiro.org/es/ad/create?type=1 Creo que Andrés lo va a arreglar en un momento.
